import test from 'node:test';import assert from 'node:assert/strict';import {accountProjection} from '../account-projection.mjs';
test('account snapshots retain dates, latest evidence and unresolved scope instead of inventing current balances',()=>{
 const context={account_snapshots:[{account:'Card',balance:100,as_of:'2026-09-01',account_type:'credit_card',purpose:'Unresolved'},{account:'Card',balance:80,as_of:'2026-10-01',account_type:'credit_card',purpose:'Unresolved'},{account:'Credit',balance:-10,as_of:'2026-09-02',account_type:'credit_card',purpose:'Household'},{account:'Loan',balance:500,as_of:'2026-10-01',account_type:'loan',purpose:'Household'}]},before=JSON.stringify(context),result=accountProjection(context,'combined','credit_card');assert.equal(result.account_count,2);assert.equal(result.reported_balance_total,70);assert.equal(result.reported_debt_total,80);assert.equal(result.mixed_dates,true);assert.equal(result.unresolved_account_count,1);assert.equal(accountProjection(context,'work','credit_card').reported_balance_total,null);assert.equal(JSON.stringify(context),before);
});
import {empty,operate} from '../core.mjs';import {rpc} from '../tools.mjs';
test('new dated snapshots append immutable history and project latest provenance through MCP',async()=>{
 const state=empty(),snapshot={months:['2026-07'],transactions:[{id:'one',account:'Fixture',merchant:'Fixture',date:'2026-07-01',month:'2026-07',amount:20,spend:20,scope:'Household',purpose:'Household',group:'Food',category:'Groceries'}],overrides:{transactions:{},budgets:{},commitments:{},notes:''}};await operate(state,'import_commit',{revision:0,idempotency_key:'account-seed',format:'dashboard_snapshot',snapshot},'fixture');
 for(const [source_id,as_of,balance] of [['older','2026-09-01',100],['newer','2026-10-01',80]])await operate(state,'import_commit',{revision:state.revision,idempotency_key:source_id,format:'runtime_evidence',evidence:{source_id,source_type:'Snapshot',source_hash:'a'.repeat(64),observed_at:'2026-10-07T00:00:00Z',payload:{account_snapshots:[{account:'Card',institution:'Fixture bank',as_of,balance,account_type:'credit_card',purpose:'Unresolved'}]}}},'fixture');
 assert.equal(state.dashboard_context.account_snapshots.length,2);const before=JSON.stringify(state),args={collection:'accounts',scope:'home',account_type:'credit_card'},direct=await operate(state,'summarize',args),remote=await rpc({id:1,method:'tools/call',params:{name:'project',arguments:{operation:'summarize',args}}},(n,a)=>operate(state,n,a));assert.deepEqual(remote.result.structuredContent,direct);assert.equal(direct.reported_debt_total,80);assert.equal(direct.items[0].source_refs[0].source_id,'newer');assert.equal(JSON.stringify(state),before);await assert.rejects(operate(state,'summarize',{...args,period:'all'}),/independent of period/);
});

test('bank balances remain separate from liability debt and mixed signed totals',()=>{const context={account_snapshots:[{account:'Bank',balance:5000,as_of:'2026-10-01',account_type:'bank',purpose:'Household'},{account:'Card',balance:100,as_of:'2026-10-01',account_type:'credit_card',purpose:'Household'}]},mixed=accountProjection(context);assert.equal(mixed.reported_debt_total,100);assert.equal(mixed.reported_bank_balance_total,5000);assert.equal(mixed.reported_balance_total,null);assert.equal(accountProjection(context,'combined','bank').reported_debt_total,0);assert.equal(mixed.balances_by_type.length,2);});
