import test from 'node:test';import assert from 'node:assert/strict';import {prepareCommitmentMoves} from '../commitment-preparation.mjs';
const document=commitment=>({transactions:{},budgets:{},commitments:{Toy:commitment},notes:''});
test('round trip preserves saved destination values and unrelated decisions',()=>{const original=document({essential:true,baselineAmount:450.01,workEssential:false,workBaselineAmount:600.01,decision:'Keep',billingFrequency:'Monthly',billingCharge:450.01}),before=JSON.stringify(original);const work=prepareCommitmentMoves(original,[{name:'Toy',to_scope:'work',seed_essential:true,seed_monthly_amount:450.01}]);assert.equal(work.prepared_decisions.commitments.Toy.workBaselineAmount,600.01);assert.equal(work.prepared_decisions.commitments.Toy.workEssential,false);const home=prepareCommitmentMoves(work.prepared_decisions,[{name:'Toy',to_scope:'home',seed_essential:false,seed_monthly_amount:600.01}]);assert.deepEqual(home.prepared_decisions.commitments.Toy,{...original.commitments.Toy,budgetScope:'home'});assert.equal(JSON.stringify(original),before);});
test('zero false and null are existing choices; absent destination fields are seeded',()=>{const original=document({baselineAmount:null,essential:false,workBaselineAmount:0,workEssential:false});for(const to_scope of ['home','work']){const result=prepareCommitmentMoves(original,[{name:'Toy',to_scope,seed_essential:true,seed_monthly_amount:20}]);assert.equal(result.planning_changes[0].seeded_fields.length,0);assert.deepEqual(result.prepared_decisions.commitments.Toy,{...original.commitments.Toy,budgetScope:to_scope});}const result=prepareCommitmentMoves(document('Keep'),[{name:'Toy',to_scope:'work',seed_essential:true,seed_monthly_amount:20}]);assert.deepEqual(result.prepared_decisions.commitments.Toy,{decision:'Keep',budgetScope:'work',workEssential:true,workBaselineAmount:20});assert.throws(()=>prepareCommitmentMoves(original,[{name:'Toy',to_scope:'work',seed_essential:true,seed_monthly_amount:20},{name:'Toy',to_scope:'home',seed_essential:true,seed_monthly_amount:20}]),/Conflicting/);});
import {empty,operate} from '../core.mjs';import {dispatch} from '../tools.mjs';
test('shared preview and save preserve both destination plans across a scope round trip',async()=>{
 const state=empty(),decisions={transactions:{},budgets:{},commitments:{'Fixture Service':{essential:true,baselineAmount:450.01,workEssential:false,workBaselineAmount:600.01,billingFrequency:'Monthly',billingCharge:20}},notes:''};await operate(state,'import_commit',{revision:0,idempotency_key:'move-seed',format:'dashboard_snapshot',snapshot:{months:['2026-07'],transactions:[{id:'bill',account:'Toy',merchant:'Fixture Service',date:'2026-07-01',amount:20,spend:20,scope:'Household',purpose:'Household',group:'Digital services',category:'Hosting'}],overrides:decisions}},'fixture');const immutable=JSON.stringify(state.sources);
 for(const to_scope of ['work','home']){const before=JSON.stringify(state),args={revision:state.revision,decisions:state.dashboard_context.overrides,edits:[],commitment_moves:[{name:'Fixture Service',to_scope,seed_essential:false,seed_monthly_amount:99}]},preview=await dispatch('project',{operation:'decision_preview',args},(n,a)=>operate(state,n,a));assert.equal(JSON.stringify(state),before);assert.equal(preview.planning_changes[0].preserved_fields.length,2);await operate(state,'decision_update',{revision:state.revision,decisions:preview.prepared_decisions},'fixture');const projection=await operate(state,'summarize',{collection:'commitments',scope:'combined'}),item=projection.items[0];assert.equal(item.assigned_scope,to_scope);assert.equal(item.baseline_monthly_amount,to_scope==='home'?450.01:600.01);assert.equal(item.essential,to_scope==='home');assert.equal(JSON.stringify(state.sources),immutable);}
});
