import test from 'node:test';import assert from 'node:assert/strict';import {contextEvidence} from '../context-evidence.mjs';
const source=(id,value)=>({source_id:id,source_type:'Snapshot',source_hash:'a'.repeat(64),observed_at:'2026-10-07T00:00:00Z',payload:{reference_notes:{note:value}}});
test('historical context matches exact field values, retains conflicts, and ignores transaction custody',()=>{
 const state={revision:7,dashboard_context:{months:['2026-09','2026-07'],reference_notes:{note:'Original'},coverage:[{name:'Toy',status:'Historical',months:{'2026-07':0}}]},runtime_evidence:{one:source('one','Original'),replay:source('one','Original'),other:source('two','Different')},sources:{transaction:{source_id:'dashboard-snapshot:any',source_type:'Snapshot'}}};const before=JSON.stringify(state),result=contextEvidence(state),note=result.fields.find(row=>row.path[0]==='reference_notes');assert.equal(note.references.length,1);assert.equal(note.conflicting_references.length,1);assert.equal(note.custody_status,'conflicting_declarations');const values=result.fields.filter(row=>row.path[0]==='coverage'&&row.path[2]==='months');assert.equal(values[0].presence,'missing');assert.equal(values[1].value,0);assert.equal(values[1].presence,'present');assert.equal(values[1].custody_status,'unknown');assert.equal(result.scope,'historical_context_unfiltered');result.months.reverse();note.value='Changed';note.references[0].field_path.push('Changed');assert.equal(JSON.stringify(state),before);
});
test('missing/null historical containers remain distinct without throwing or manufacturing references',()=>{
 for(const coverage of [null,'old malformed container']){const result=contextEvidence({revision:2,dashboard_context:{coverage}});assert.equal(result.fields.find(row=>row.path[0]==='coverage').value,coverage);assert.equal(result.fields.find(row=>row.path[0]==='reference_notes').presence,'missing');assert.equal(result.fields.every(row=>row.references.length===0),true);}
});

test('inconsistent duplicate custody is conflicting and malformed metadata never aliases state',()=>{
 const one=source('same','Original'),other={...source('same','Original'),observed_at:'2026-10-08T00:00:00Z'},bad={...source('bad','Original'),source_hash:['a'.repeat(64)]};
 const state={revision:1,dashboard_context:{reference_notes:{note:'Original'}},runtime_evidence:{one,other,bad}},before=JSON.stringify(state);const note=contextEvidence(state).fields.find(row=>row.path[0]==='reference_notes');assert.equal(note.references.length,0);assert.equal(note.conflicting_references.length,3);assert.equal(note.custody_status,'conflicting_declarations');assert.equal(note.conflicting_references.find(ref=>ref.source_id==='bad').source_hash,null);note.conflicting_references[0].field_path.push('mutate');assert.equal(JSON.stringify(state),before);
});

import {empty,operate} from '../core.mjs';import {rpc} from '../tools.mjs';
test('snapshot query composes identical MCP custody and rejects misleading financial filters',async()=>{
 const state=empty();await operate(state,'import_commit',{revision:0,idempotency_key:'context-seed',format:'dashboard_snapshot',snapshot:{months:['2026-07'],transactions:[{id:'toy',account:'Toy',merchant:'Toy',date:'2026-07-01',amount:1,spend:1,scope:'Household',purpose:'Household',group:'Food',category:'Groceries'}],overrides:{transactions:{},budgets:{},commitments:{},notes:''},reference_notes:{note:'Historical'}}},'fixture');
 const before=JSON.stringify(state),direct=await operate(state,'query',{collection:'snapshot'}),remote=await rpc({id:1,method:'tools/call',params:{name:'query',arguments:{collection:'snapshot'}}},(name,args)=>operate(state,name,args));assert.deepEqual(remote.result.structuredContent,direct);assert.equal(direct.context_evidence.revision,state.revision);assert.equal(direct.context_evidence.fields.find(row=>row.path[0]==='reference_notes').custody_status,'unknown');await assert.rejects(operate(state,'query',{collection:'snapshot',scope:'home'}),/unfiltered/);assert.equal(JSON.stringify(state),before);
});
test('discovery exposes detached context schema matching actual snapshot descriptor fields',async()=>{
 const state=empty(),docs=await operate(state,'docs');assert.equal(docs.context_evidence_contract,'context-custody@1');const projection=contextEvidence({revision:0,dashboard_context:{reference_notes:{note:'Toy'}},runtime_evidence:{one:source('one','Toy')}}),schema=docs.context_evidence_schema;assert.deepEqual(Object.keys(projection).sort(),schema.required.toSorted());for(const field of projection.fields){assert.deepEqual(Object.keys(field).sort(),schema.properties.fields.items.required.toSorted());for(const ref of field.references)assert.deepEqual(Object.keys(ref).sort(),schema.properties.fields.items.properties.references.items.required.toSorted());}schema.properties.fields.items.required.push('mutated');assert.equal((await operate(state,'docs')).context_evidence_schema.properties.fields.items.required.includes('mutated'),false);
});
