import test from 'node:test';import assert from 'node:assert/strict';import {contextFieldText,coreMoneyCard} from '../frontend/context-evidence.js';
test('context formatting preserves known zero and labels old evidence without rewriting its revision',()=>{const snapshot={_revision:3,context_evidence:{revision:2,fields:[{path:['coverage',0,'months','2026-07'],presence:'present',value:0,label:'Historical context · original custody unknown'}]}};const before=JSON.stringify(snapshot);assert.match(contextFieldText(snapshot,['coverage',0,'months','2026-07']),/^0 · Historical/);assert.match(contextFieldText(snapshot,['coverage',0,'months','2026-07']),/earlier revision/);assert.equal(contextFieldText(snapshot,['missing']),'Historical reference unavailable');assert.equal(JSON.stringify(snapshot),before);});
test('money card only formats shared amounts and keeps missing amounts unavailable',()=>{assert.deepEqual(coreMoneyCard('Toy',12,'Note',String),['Toy','Unavailable','Shared metric unavailable']);assert.deepEqual(coreMoneyCard('Toy',{period_total:12,recorded_average_per_selected_month:null},'Note',String),['Toy','Unavailable','12 period total · Note']);assert.equal(coreMoneyCard('Toy',{period_total:12,recorded_average_per_selected_month:4},'Note',String)[1],'4/mo');});
import {readFileSync} from 'node:fs';import vm from 'node:vm';
test('shared context refresh marks notes, status and coverage stale together after revision advance',()=>{
 const source=readFileSync(new URL('../frontend/controller.js',import.meta.url),'utf8'),helper=source.slice(source.indexOf('function refreshContextDisplay(){'),source.indexOf('\n}\n',source.indexOf('function refreshContextDisplay(){'))+2);
 const fields=[{path:['source_status'],value:'Historical feed'},{path:['as_of'],value:'2026-10-06'},{path:['reference_notes','note'],value:'Note'},{path:['coverage',0,'name'],value:'Toy'},{path:['coverage',0,'status'],value:'Unknown'},{path:['coverage',0,'months','2026-07'],value:0}].map(field=>({...field,presence:'present',label:'Historical context · original custody unknown'}));
 const data={_revision:2,coverage:[{}],context_evidence:{revision:1,months:['2026-07'],fields}},status={},note={dataset:{referenceNote:'note'}},calls=[];
 vm.runInNewContext(helper+';refreshContextDisplay();',{data,contextFieldText,$:()=>status,table:(...args)=>calls.push(args),referenceNote:key=>contextFieldText(data,['reference_notes',key]),globalThis:{document:{querySelectorAll:()=>[note]}}});
 assert.match(status.textContent,/earlier revision/);assert.match(note.textContent,/earlier revision/);assert.deepEqual(Array.from(calls[0][1]),['Account','2026-07 records','Source status']);assert.equal(calls[0][2][0].every(value=>value.includes('earlier revision')),true);assert.equal(data.context_evidence.revision,1);
});
