import test from 'node:test';import assert from 'node:assert/strict';import {createDecisionPreviewGate} from '../frontend/decision-preview.js';
test('preview gate rejects changed editor, revision, field and sibling draft while retaining current preview',async()=>{for(const key of ['editor','revision','fields','decisions']){let context={revision:1,editor:1,transaction_id:'toy',fields:{purpose:'Household'},decisions:{notes:''}},resolve;const gate=createDecisionPreviewGate({getContext:()=>context,request:()=>new Promise(r=>resolve=r)});const pending=gate.read();context={...context,[key]:key==='fields'?{purpose:'Business'}:key==='decisions'?{notes:'New'}:2};resolve({revision:1,prepared_decisions:{},suggestions:[]});assert.equal(await pending,null);}const context={revision:1,editor:1,transaction_id:'toy',fields:{purpose:'Household'},decisions:{notes:''}},gate=createDecisionPreviewGate({getContext:()=>context,request:async()=>({revision:1,prepared_decisions:{},suggestions:[]})});assert.equal(gate.isCurrent(await gate.read()),true);});
test('closed editor invalidates pending preview and revision-mismatched response fails',async()=>{const context={revision:1,editor:1,transaction_id:'toy',fields:{},decisions:{}},gate=createDecisionPreviewGate({getContext:()=>context,request:async()=>({revision:2})});await assert.rejects(gate.read(),/revision/);let resolve;const pendingGate=createDecisionPreviewGate({getContext:()=>context,request:()=>new Promise(r=>resolve=r)}),pending=pendingGate.read();pendingGate.invalidate();resolve({revision:1});assert.equal(await pending,null);});
import {readFileSync} from 'node:fs';import vm from 'node:vm';
import {empty,operate} from '../core.mjs';
test('actual editor omits untouched legacy fields and does not close newer editor choices after save',async()=>{
 for(const change of ['new-editor','new-choice','new-sibling']){
  const state=empty(),record={id:'toy',account:'Toy',merchant:'Toy',date:'2026-07-01',amount:20,spend:20,scope:'Household',purpose:'Household',group:'Travel',category:'Flight',travel_purpose:'Personal / family',inflow_role:'Mixed business income / reimbursement'},decisions={transactions:{},budgets:{},commitments:{},notes:''};await operate(state,'import_commit',{revision:0,idempotency_key:'ui-seed',format:'dashboard_snapshot',snapshot:{months:['2026-07'],transactions:[record],overrides:decisions}},'fixture');
  const source=readFileSync(new URL('../frontend/controller.js',import.meta.url),'utf8'),editor=source.slice(source.indexOf('function edit(id){'),source.indexOf('const queuedSave=createSaveQueue(')),node=(tag,text)=>({tag,text,textContent:text,children:[],hidden:false,value:'',append(...children){this.children.push(...children)},replaceChildren(...children){this.children=children},setAttribute(){},scrollIntoView(){}}),box=node('div'),bodies=[];let finishSave;
  const context={editorGeneration:0,rows:()=>[record],$:()=>box,element:node,Option:function(text,value){this.text=text;this.value=value;},money:String,groups:['Travel','Insurance'],data:{_revision:1},overrides:decisions,createDecisionPreviewGate,queuedSave:{pending:0},recordSourceReader:{show(){},invalidate(){}},render(){},structuredClone,fetch:async(_url,options)=>{const body=JSON.parse(options.body);bodies.push(body);return {ok:true,json:()=>operate(state,'decision_preview',body.args.args)};},save:()=>new Promise(resolve=>finishSave=resolve)};
  vm.runInNewContext(editor+';edit("toy");',context);const category=box.children.find(child=>child.text==='Subcategory').children[0];category.value='Explicit category';assert.equal(context.editorHasUnsavedChanges(),true);const save=box.children.find(child=>child.text==='Review and save classification'),firstPreview=save.onclick();await firstPreview;const pending=save.onclick();await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(bodies[0].args.args.edits[0].fields,{purpose:'Household',category:'Explicit category'});assert.equal(context.overrides.transactions.toy.inflow_role,undefined);if(change==='new-editor')context.editorGeneration++;else if(change==='new-choice')category.value='Newer category';else context.overrides.notes='Newer sibling';finishSave(change==='new-sibling'?{ok:true,current:false}:true);await pending;assert.equal(box.hidden,false);if(change==='new-choice'||change==='new-sibling'){category.value='Flight';await save.onclick();const reverted=save.onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(bodies.at(-1).args.args.edits[0].fields.category,'Flight');finishSave(true);await reverted;assert.equal(box.hidden,true);assert.equal(context.editorHasUnsavedChanges(),false);}
 }
});
