import test from 'node:test';import assert from 'node:assert/strict';import {empty,operate} from '../core.mjs';import {dispatch} from '../tools.mjs';
async function fixture(){const state=empty(),decisions={transactions:{},budgets:{},commitments:{},notes:''};await operate(state,'import_commit',{revision:0,idempotency_key:'preview-seed',format:'dashboard_snapshot',snapshot:{months:['2026-07'],transactions:[{id:'toy',account:'Toy',merchant:'Toy',date:'2026-07-01',amount:20,spend:20,scope:'Household',purpose:'Household',group:'Travel',category:'Flight'}],overrides:decisions}},'fixture');return {state,decisions};}
test('explicit household Work travel is preserved with a separate suggestion across dispatch and core',async()=>{const {state,decisions}=await fixture(),before=JSON.stringify(state),args={revision:1,decisions,edits:[{transaction_id:'toy',fields:{purpose:'Household',group:'Travel',category:'Flight',travel_purpose:'Work',inflow_role:'Unresolved'}}]};const direct=await operate(state,'decision_preview',args),surface=await dispatch('project',{operation:'decision_preview',args},(n,a)=>operate(state,n,a));assert.deepEqual(surface,direct);assert.equal(direct.prepared_decisions.transactions.toy.purpose,'Household');assert.equal(direct.prepared_decisions.transactions.toy.inflow_role,'');assert.equal(direct.suggestions[0].proposed_value,'Business');assert.equal(JSON.stringify(state),before);await operate(state,'decision_update',{revision:1,decisions:direct.prepared_decisions},'fixture');assert.equal(state.transactions.toy.classification.purpose,'Household');assert.equal(state.reviews.length,0);});
test('preview preserves explicit insurance category, untouched legacy fields and state on invalid edits',async()=>{const {state,decisions}=await fixture();decisions.transactions.toy={evidence:'Legacy',travel_city:'Toy city'};const args={revision:1,decisions,edits:[{transaction_id:'toy',fields:{group:'Insurance',category:'My explicit category',insurance_type:'Pet'}}]},before=JSON.stringify(state);const result=await operate(state,'decision_preview',args);assert.equal(result.prepared_decisions.transactions.toy.category,'My explicit category');assert.equal(result.prepared_decisions.transactions.toy.evidence,'Legacy');assert.equal(result.suggestions[0].proposed_value,'Pet insurance');result.prepared_decisions.transactions.toy.evidence='Changed';assert.equal(decisions.transactions.toy.evidence,'Legacy');for(const edits of [[{transaction_id:'missing',fields:{purpose:'Business'}}],[{transaction_id:'toy',fields:{amount:'9'}}],[{transaction_id:'toy',fields:{purpose:'Household'}},{transaction_id:'toy',fields:{purpose:'Business'}}]])await assert.rejects(operate(state,'decision_preview',{...args,edits}));await assert.rejects(operate(state,'decision_preview',{...args,revision:0}),/Revision/);assert.equal(JSON.stringify(state),before);});
test('preview leaves accepted review history unchanged and does not normalize unedited legacy fields',async()=>{const {state,decisions}=await fixture();state.reviews.push({id:'historical-review',transaction_id:'toy',status:'accepted',classification:{purpose:'Household',group:'Travel',category:'Flight'},evidence:'Synthetic historical review'});decisions.transactions.toy={inflow_role:'Unresolved'};const before=JSON.stringify(state),result=await operate(state,'decision_preview',{revision:1,decisions,edits:[]});assert.equal(result.prepared_decisions.transactions.toy.inflow_role,'Unresolved');assert.equal(result.suggestions.length,0);assert.equal(JSON.stringify(state),before);await assert.rejects(operate(state,'decision_preview',{revision:1,decisions,edits:[{transaction_id:'toy',fields:{travel_purpose:'Unsupported'}}]}),/choice/);});
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';import {store} from '../store.mjs';
test('actual HTTP and stdio preview match core while a write lock is held, without any state change',async()=>{
 const {state,decisions}=await fixture(),dir=await fs.mkdtemp(path.join(os.tmpdir(),'finance-preview-')),file=path.join(dir,'state.json'),token='synthetic-preview-token-0123456789012345',env={...process.env,FINANCE_STATE_FILE:file,FINANCE_HTTP_TOKEN:token,FINANCE_PORT:'18769'};let server;
 try{const bytes=JSON.stringify(state);await fs.writeFile(file,bytes);await fs.writeFile(file+'.lock','synthetic held writer');const args={revision:1,decisions,edits:[{transaction_id:'toy',fields:{travel_purpose:'Work',purpose:'Household'}}]},direct=await operate(state,'decision_preview',args);assert.deepEqual(await store(file,'fixture')('decision_preview',args),direct);server=spawn(process.execPath,['http.mjs'],{cwd:new URL('..',import.meta.url),env,stdio:['ignore','pipe','pipe']});let ready=false;for(let n=0;n<50;n++){try{const response=await fetch('http://127.0.0.1:18769/api/capability',{method:'POST'});if(response.status===401){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,20));}assert.equal(ready,true);const response=await fetch('http://127.0.0.1:18769/api/capability',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({name:'project',args:{operation:'decision_preview',args}})});assert.equal(response.status,200);assert.deepEqual(await response.json(),direct);const child=spawn(process.execPath,['mcp.mjs'],{cwd:new URL('..',import.meta.url),env});let output='';child.stdout.on('data',data=>output+=data);child.stdin.end(JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'project',arguments:{operation:'decision_preview',args}}})+'\n');await once(child,'exit');assert.deepEqual(JSON.parse(output.trim()).result.structuredContent,direct);assert.equal(await fs.readFile(file,'utf8'),bytes);assert.equal(await fs.readFile(file+'.lock','utf8'),'synthetic held writer');
 }finally{if(server&&server.exitCode===null){server.kill();await once(server,'exit');}await fs.rm(dir,{recursive:true,force:true});}
});
test('preview effective purpose agrees with post-save records for explicit and omitted purpose',async()=>{
 for(const explicit of [false,true]){const {state,decisions}=await fixture(),fields={travel_purpose:'Work',...(explicit?{purpose:'Household'}:{})};const preview=await operate(state,'decision_preview',{revision:1,decisions,edits:[{transaction_id:'toy',fields}]});assert.equal(preview.effective_record_states[0].purpose,explicit?'Household':'Business');assert.equal(preview.suggestions.length,explicit?1:0);await operate(state,'decision_update',{revision:1,decisions:preview.prepared_decisions},'fixture');const records=await operate(state,'query',{collection:'records',scope:'combined',period:'all'});assert.equal(records.items[0].purpose,preview.effective_record_states[0].purpose);assert.equal(records.items[0].group,preview.effective_record_states[0].group);assert.equal(records.items[0].category,preview.effective_record_states[0].category);}
});
test('preview separates effective purpose from core scope attribution without changing legacy inflow rules',async()=>{
 for(const mixed of [false,true]){const {state,decisions}=await fixture();if(mixed)state.transactions.toy.attributes.inflow_role='Mixed business income / reimbursement';const preview=await operate(state,'decision_preview',{revision:1,decisions,edits:[{transaction_id:'toy',fields:{travel_purpose:'Work',purpose:'Household'}}]});const effective=preview.effective_record_states[0];assert.equal(effective.purpose,'Household');assert.equal(effective.effective_scope,mixed?'work':'home');assert.equal(effective.scope_reason,mixed?'mixed_business_inflow':'home_default');await operate(state,'decision_update',{revision:1,decisions:preview.prepared_decisions},'fixture');assert.equal((await operate(state,'query',{collection:'records',scope:effective.effective_scope,period:'all'})).items.length,1);}
});
