import test from 'node:test';import assert from 'node:assert/strict';import {evidenceProjection} from '../evidence-projection.mjs';
test('evidence deduplicates split parents and leaves unavailable feed counts unknown',()=>{
 const rows=[{id:'one-a',parent_transaction_id:'one',account:'Fixture',account_key:'fixture',month:'2026-07',source:'Apple CSV'}, {id:'one-b',parent_transaction_id:'one',account:'Fixture',account_key:'fixture',month:'2026-07',source:'Apple CSV',receipt_path:'fixture.txt'}],before=JSON.stringify(rows);
 const report=evidenceProjection(rows,['2026-07','2026-08'],{fixture:{'2026-07':0}});assert.equal(report.rr.length,1);assert.equal(report.linked.length,1);assert.equal(report.accounts[0].monthly[0].statement_count,1);assert.equal(report.accounts[0].monthly[0].era_original_count,0);assert.equal(report.totals[1].era_original_count,null);assert.equal(report.complete,false);assert.equal(report.summary[1].record_count,1);assert.equal(report.evidence_types[1].linked_count,null);assert.equal(report.evidence_types[1].reconciliation_status,'Not certified');assert.equal(JSON.stringify(rows),before);
});
import {empty,operate} from '../core.mjs';import {rpc} from '../tools.mjs';
test('evidence projection through MCP matches core and preserves source state',async()=>{
 const snapshot={months:['2026-07','2026-08'],transactions:[{id:'one',account:'Fixture',account_key:'fixture',merchant:'Fixture market',date:'2026-07-01',month:'2026-07',amount:20,spend:20,scope:'Household',purpose:'Household',group:'Food',category:'Groceries',source:'Apple CSV'}],overrides:{transactions:{},budgets:{},commitments:{},notes:''},original_era_monthly_counts:{fixture:{'2026-07':2}}};
 const state=empty();await operate(state,'import_commit',{revision:0,idempotency_key:'evidence-fixture',format:'dashboard_snapshot',snapshot},'fixture');const before=JSON.stringify(state),args={collection:'evidence',scope:'home',period:'all',hide_reimbursed:false},direct=await operate(state,'summarize',args);
 const remote=await rpc({id:1,method:'tools/call',params:{name:'project',arguments:{operation:'summarize',args}}},(name,args)=>operate(state,name,args));assert.deepEqual(remote.result.structuredContent,direct);assert.equal(direct.accounts[0].monthly[0].era_original_count,2);assert.equal(direct.accounts[0].monthly[1].era_original_count,null);assert.equal(direct.accounts[0].monthly[0].statement_count,1);assert.equal(direct.accounts[0].monthly[0].source_refs[0].source_type,'Snapshot');assert.equal(JSON.stringify(state),before);
 await assert.rejects(operate(state,'summarize',{...args,series:true}),/Evidence projection accepts/);
});
