import test from 'node:test';import assert from 'node:assert/strict';
import {givingEvidence} from '../giving-evidence.mjs';import {empty,operate} from '../core.mjs';import {rpc} from '../tools.mjs';
test('giving evidence filters receipt dates, separates unresolved attribution and never certifies candidates',()=>{
 const all=[{id:'home',source_refs:[{source_id:'fixture',source_line:'1'}]},{id:'work'},{id:'mixed-home',parent_transaction_id:'mixed'},{id:'mixed-work',parent_transaction_id:'mixed'}],selected=[all[0],all[2]],trail={app_receipts:[{id:'a',date:'2026-07-01',amount:10.01,ledger_id:'home'},{id:'a',date:'2026-07-01',amount:10.01,ledger_id:'home'},{id:'outside',date:'2026-07-02',amount:90,ledger_id:'work'},{id:'old',date:'2026-06-01',amount:100,ledger_id:'home'},{id:'unknown',date:'2026-07-03',amount:20,ledger_id:'missing'},{id:'mixed',date:'2026-07-04',amount:30,ledger_id:'mixed'}],trail:[{funding_id:'home',funding_date:'2026-07-01',funding_amount:100,final_payment_candidates:[{id:'candidate'}]}]},before=JSON.stringify(trail);
 const result=givingEvidence(trail,all,selected,['2026-07']);assert.equal(result.receipt_count,1);assert.equal(result.observed_receipt_total,10.01);assert.equal(result.unresolved_receipt_count,2);assert.equal(result.funding_candidate_count,1);assert.equal(result.reconciliation_status,'Not certified');assert.equal(result.receipts[0].source_refs.length,0);assert.equal(result.receipts[0].ledger_scope_refs.length,1);assert.equal(result.context_custody_status,'Historical context custody not established');assert.equal(JSON.stringify(trail),before);
});
test('conflicting receipt identities and invalid amounts cannot inflate attributed totals',()=>{
 const rows=[{id:'home'}],trail={app_receipts:[{id:'a',date:'2026-06-01',amount:10,ledger_id:'home'},{id:'a',date:'2026-07-01',amount:20,ledger_id:'home'},{id:'bad',date:'2026-07-01',amount:-10,ledger_id:'home'}]};const result=givingEvidence(trail,rows,rows,['2026-07']);assert.equal(result.receipt_count,0);assert.equal(result.observed_receipt_total,0);assert.equal(result.unresolved_receipt_count,2);
});
test('giving context projects identically through core and MCP without changing evidence or decisions',async()=>{
 const snapshot={months:['2026-07','2026-08'],transactions:[{id:'gift',account:'Fixture',merchant:'Fixture giving',date:'2026-07-01',month:'2026-07',amount:10,spend:10,scope:'Household',purpose:'Household',group:'Giving',category:'Tithe'}],overrides:{transactions:{},budgets:{},commitments:{},notes:''},giving_trail:{app_receipts:[{id:'receipt',date:'2026-07-01',amount:10,ledger_id:'gift'}]}};
 const state=empty();await operate(state,'import_commit',{revision:0,idempotency_key:'giving-fixture',format:'dashboard_snapshot',snapshot},'fixture');const before=JSON.stringify(state),args={collection:'evidence',scope:'home',period:'2026-07'},direct=await operate(state,'summarize',args),remote=await rpc({id:1,method:'tools/call',params:{name:'project',arguments:{operation:'summarize',args}}},(name,args)=>operate(state,name,args));assert.deepEqual(remote.result.structuredContent,direct);assert.equal(direct.giving_trail.observed_receipt_total,10);assert.equal((await operate(state,'summarize',{...args,period:'2026-08'})).giving_trail.receipt_count,0);assert.equal(JSON.stringify(state),before);
});

test('receipt date selects the month independently of the scoped ledger date',async()=>{
 const snapshot={months:['2026-07'],transactions:[{id:'gift',account:'Fixture',merchant:'Fixture giving',date:'2026-06-30',month:'2026-06',amount:10,spend:10,scope:'Household',purpose:'Household',group:'Giving',category:'Tithe'}],overrides:{transactions:{},budgets:{},commitments:{},notes:''},giving_trail:{app_receipts:[{id:'receipt',date:'2026-07-01',amount:10,ledger_id:'gift'}],trail:[{funding_id:'gift',funding_date:'2026-07-01',funding_amount:10}]}};
 const state=empty();await operate(state,'import_commit',{revision:0,idempotency_key:'giving-dates',format:'dashboard_snapshot',snapshot},'fixture');const report=await operate(state,'summarize',{collection:'evidence',scope:'home',period:'2026-07'});assert.equal(report.giving_trail.receipt_count,1);assert.equal(report.giving_trail.funding_candidate_count,1);assert.equal((await operate(state,'summarize',{collection:'evidence',scope:'work',period:'2026-07'})).giving_trail.receipt_count,0);
});
