import test from 'node:test';import assert from 'node:assert/strict';import {recordQuery} from '../record-query.mjs';
test('record selection summaries describe all matches rather than one page',()=>{
 const rows=[{id:'b',date:'2026-07-01',merchant:'Market',description:'Food',account:'Fixture',scope:'Household',spend:10.01},{id:'a',date:'2026-07-01',merchant:'Market',account:'Fixture',scope:'Household',spend:20.02}],before=JSON.stringify(rows),result=recordQuery(rows,['2026-07','2026-08'],{search:'market',limit:1});assert.equal(result.items[0].id,'a');assert.equal(result.total,2);assert.equal(result.next_offset,1);assert.equal(result.summary.spending.period_total,30.03);assert.equal(result.summary.spending.recorded_average_per_selected_month,15.02);assert.equal(JSON.stringify(rows),before);assert.throws(()=>recordQuery(rows,['2026-07'],{limit:201}),/pagination/);
});
import {empty,operate} from '../core.mjs';import {rpc} from '../tools.mjs';
test('record queries expose the same full-match summary and provenance through MCP',async()=>{
 const snapshot={months:['2026-07'],transactions:[{id:'one',account:'Fixture',merchant:'Market',date:'2026-07-01',month:'2026-07',amount:20,spend:20,scope:'Household',purpose:'Household',group:'Food',category:'Groceries'}],overrides:{transactions:{},budgets:{},commitments:{},notes:''}},state=empty();await operate(state,'import_commit',{revision:0,idempotency_key:'record-fixture',format:'dashboard_snapshot',snapshot},'fixture');const before=JSON.stringify(state),args={collection:'records',scope:'home',search:'market',limit:1},direct=await operate(state,'query',args),remote=await rpc({id:1,method:'tools/call',params:{name:'query',arguments:args}},(n,a)=>operate(state,n,a));assert.deepEqual(remote.result.structuredContent,direct);assert.equal(direct.items[0].source_refs[0].source_type,'Snapshot');assert.equal(direct.summary.record_count,1);assert.equal(JSON.stringify(state),before);
});

test('explicit record selections preserve an empty selection and summaries across pages',()=>{const rows=[{id:'one',date:'2026-07-01',account:'Fixture',scope:'Household',spend:20},{id:'two',date:'2026-07-01',account:'Fixture',scope:'Household',spend:30}];assert.equal(recordQuery(rows,['2026-07'],{record_ids:[]}).total,0);assert.equal(recordQuery(rows,['2026-07'],{record_ids:['two']}).summary.spending.period_total,30);assert.throws(()=>recordQuery(rows,['2026-07'],{record_ids:'two'}),/selection/);});
