import test from 'node:test';import assert from 'node:assert/strict';import {validateRuntimeEvidence} from '../runtime-evidence.mjs';
const fixture={source_id:'fixture-runtime',source_type:'Snapshot',source_hash:'a'.repeat(64),observed_at:'2026-10-07T00:00:00.000Z',payload:{reference_notes:{one:'Synthetic reference'},original_era_monthly_counts:{fixture:{'2026-07':0}},account_snapshots:[{account:'Fixture card',institution:'Fixture bank',balance:100,as_of:'2026-10-06',account_type:'credit_card',purpose:'Unresolved'}]}};
test('runtime evidence retains source identity and known-zero inventory without mutating input',()=>{const before=JSON.stringify(fixture),result=validateRuntimeEvidence(fixture);assert.deepEqual(result,fixture);result.payload.account_snapshots[0].balance=200;assert.equal(JSON.stringify(fixture),before);});
test('runtime evidence rejects mislabeled provenance, unknown fields and invalid counts',()=>{for(const invalid of [{...fixture,source_type:'Era'},{...fixture,payload:{html:'private raw document'}},{...fixture,payload:{original_era_monthly_counts:{fixture:{'2026-07':-1}}}}])assert.throws(()=>validateRuntimeEvidence(invalid));});

test('observation timestamps require valid UTC calendar and clock fields',()=>{for(const observed_at of ['2026-02-30T00:00:00Z','2026-10-07T12:00:00','2026-10-07T24:00:00Z'])assert.throws(()=>validateRuntimeEvidence({...fixture,observed_at}),/runtime evidence/);assert.equal(validateRuntimeEvidence({...fixture,observed_at:'2026-10-07T12:00:00Z'}).observed_at,'2026-10-07T12:00:00.000Z');});
import {planRuntimeEvidence} from '../runtime-evidence.mjs';
test('runtime import planning fills missing context without overwriting decisions or evidence',()=>{
 const state={dashboard_context:{overrides:{notes:'Preserve'},original_era_monthly_counts:{fixture:{'2026-06':1}}},transactions:{one:{amount:20}},sources:{original:{source_type:'Statement'}}},before=JSON.stringify(state),plan=planRuntimeEvidence(state,fixture);assert.equal(plan.draft.dashboard_context.overrides.notes,'Preserve');assert.equal(plan.draft.dashboard_context.original_era_monthly_counts.fixture['2026-06'],1);assert.equal(plan.draft.dashboard_context.original_era_monthly_counts.fixture['2026-07'],0);assert.deepEqual(plan.draft.transactions,state.transactions);assert.deepEqual(plan.draft.sources,state.sources);assert.equal(JSON.stringify(state),before);
 const replay=planRuntimeEvidence(plan.draft,fixture);assert.equal(replay.result.new_context_entries,0);assert.equal(replay.result.new_runtime_sources,0);
 const changed=structuredClone(fixture);changed.source_id='different';changed.payload.account_snapshots[0].balance=500;assert.throws(()=>planRuntimeEvidence(plan.draft,changed),/conflicts/);
});
import {empty,operate} from '../core.mjs';import {rpc} from '../tools.mjs';
test('runtime evidence imports are previewable, idempotent, revisioned and exposed through MCP',async()=>{
 const state=empty(),snapshot={months:['2026-07'],transactions:[{id:'one',account:'Fixture',merchant:'Fixture',date:'2026-07-01',month:'2026-07',amount:20,spend:20,scope:'Household',purpose:'Household',group:'Food',category:'Groceries'}],overrides:{transactions:{},budgets:{},commitments:{},notes:'Preserve'}};await operate(state,'import_commit',{revision:0,idempotency_key:'runtime-seed',format:'dashboard_snapshot',snapshot},'fixture');
 const before=JSON.stringify(state),args={format:'runtime_evidence',evidence:fixture};const preview=await operate(state,'import_preview',args);assert.equal(preview.new_runtime_sources,1);assert.equal(JSON.stringify(state),before);
 const command={...args,revision:1,idempotency_key:'runtime-evidence-fixture'},remote=await rpc({id:1,method:'tools/call',params:{name:'execute',arguments:{operation:'import_commit',args:command}}},(n,a)=>operate(state,n,a,'fixture'));assert.equal(remote.result.structuredContent.revision,2);assert.equal(state.dashboard_context.overrides.notes,'Preserve');assert.equal(state.dashboard_context.runtime_evidence_refs[fixture.source_id].source_type,'Snapshot');assert.equal(Object.keys(state.transactions).length,1);
 const saved=JSON.stringify(state);await assert.rejects(operate(state,'import_commit',{...command,rows:[]},'fixture'),/cannot also include/);assert.deepEqual(await operate(state,'import_commit',command,'fixture'),remote.result.structuredContent);assert.equal(JSON.stringify(state),saved);const changed=structuredClone(fixture);changed.payload.reference_notes.one='Changed';await assert.rejects(operate(state,'import_commit',{...command,evidence:changed},'fixture'),/Idempotency content conflict/);assert.equal(JSON.stringify(state),saved);
});
