import {recordSourceNode,createRecordSourceReader} from './record-source.js';
import {createSourceInspector} from './source-inspector.js';
import {createSaveQueue,loadWithSaveGuard} from './save-queue.js';
import {commitmentDecision} from '../commitment-projection.mjs';
import {classificationGroups,sum,purchasePlace,billName,scopeRows,dashboardRows,planningItems as sharedPlanningItems} from "../dashboard-domain.mjs";
export function startDashboard(){
function referenceNote(key){return data.reference_notes?.[key]||"Reference evidence awaiting runtime migration";}



const embedded={"months": ["2026-07", "2026-08", "2026-09"], "transactions": [], "coverage": [], "overrides": {"transactions": {}, "budgets": {}, "commitments": {}, "notes": ""}, "expected_wife_contributions": {}, "giving_trail": {"trail": [], "monthly": {}}, "source_status": "Loading protected data", "as_of": ""};
let data=embedded,overrides=data.overrides,activeTab='overview',groupSelected='Housing',limit=60,transactionReport=null,transactionRequest=0,recordSelection=null;
let confirmedDecisions=structuredClone(overrides);
const hasUnsavedChanges=()=>JSON.stringify(overrides)!==JSON.stringify(confirmedDecisions);
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n),short=n=>'$'+Math.round(n).toLocaleString('en-US');
let currentReport=null,allReport=null,chartReport=null,projectionRequest=0,detailReports=[],planningReport=null,evidenceReport=null,cashReports=[],accountReport=null;
const recordSourceReader=createRecordSourceReader({getRevision:()=>data._revision,request:async args=>{const response=await fetch('/api/capability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'query',args})});const body=await response.json();if(!response.ok)throw Error(body.error||'Source query failed');return body;}});
const sourceInspector=createSourceInspector({host:$('source-observations'),status:$('source-observation-status'),more:$('more-source-observations'),getContext:()=>({revision:data._revision,scope:localStorage.getItem('home-budget-overview-scope')||'combined',months:$('source-date-filter').value==='all'?null:$('period').value==='all'?data.months:[$('period').value]}),request:async args=>{const response=await fetch('/api/capability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'query',args})});const body=await response.json();if(!response.ok)throw Error(body.error||'Source query failed');return body;}});
$('source-date-filter').onchange=()=>sourceInspector.refresh();
const detailDimensions=[['kind','group','merchant'],['kind','group','category'],['kind','group','category','merchant'],['kind','group','category','detail'],['kind','group','category','detail','merchant'],['kind','group','travel_purpose'],['kind','group','travel_purpose','merchant'],['kind','purpose']];
function detailSeries(dimensions,filters={}){return (detailReports.find(report=>JSON.stringify(report.dimensions)===JSON.stringify(dimensions))?.series||[]).filter(series=>series.dimensions.kind==='spending_commitment'&&Object.entries(filters).every(([key,value])=>series.dimensions[key]===value));}
const reportSeries=(report,group)=>report?.series.find(r=>r.dimensions.kind==='spending_commitment'&&r.dimensions.group===group);
const reportMeasure=(key)=>currentReport?.measures[key]?.period_total??0;
async function render(){
 ++transactionRequest;transactionReport=null;
 const sequence=++projectionRequest,scope=localStorage.getItem('home-budget-overview-scope')||'combined',period=$('period').value,hide_reimbursed=$('hide-reimbursed').checked;
 try{
  const request=async(extra)=>{const res=await fetch('/api/capability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'project',args:{operation:'summarize',args:{collection:'flows',scope,period,hide_reimbursed,series:true,...extra}}})});const body=await res.json();if(!res.ok)throw Error(body.error||'Projection failed');return body;};
  const planRequest=async()=>{const res=await fetch('/api/capability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'project',args:{operation:'summarize',args:{collection:'commitments',scope}}})});const body=await res.json();if(!res.ok)throw Error(body.error||'Planning projection failed');return body;};
  const accountRequest=async()=>{const res=await fetch('/api/capability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'project',args:{operation:'summarize',args:{collection:'accounts',scope,account_type:'credit_card'}}})});const body=await res.json();if(!res.ok)throw Error(body.error||'Account projection failed');return body;};
  const results=await Promise.all([request({rollups:detailDimensions}),request({period:'all',rollups:[['kind'],['kind','payment_channel']]}),request({kind:'spending_commitment',groups:[...visibleGroups]}),planRequest(),request({collection:'evidence',series:undefined}),accountRequest()]);
  if(sequence!==projectionRequest)return;
  if(results.some(r=>r.revision!==data._revision))throw Error('Source revision changed; reload before continuing');
  [currentReport,allReport,chartReport]=results.map(r=>r.projection);detailReports=results[0].rollups||[];planningReport=results[3];evidenceReport=results[4];cashReports=results[1].rollups||[];accountReport=results[5];$('baseline-mode').value=scope;renderContent();
 }catch(error){if(sequence!==projectionRequest)return;sourceInspector.clear();currentReport=allReport=chartReport=planningReport=evidenceReport=accountReport=transactionReport=null;detailReports=[];cashReports=[];++transactionRequest;['page-heroes','inflow-summary','kpis','outflow-kpis','chart','legend','category-table','category-title','category-detail','big-categories','cash-table','inflow-review','purpose-bars','wife-plan','funding-summary','commitment-summary','commitment-table','budget-table','budget-summary','transaction-table','transaction-count','card-snapshot-summary','card-snapshot-table','card-snapshot-status','baseline-summary','baseline-category-heroes','baseline-table','subscription-summary','subscription-table','source-reconciliation','account-source-months','coverage-table'].forEach(id=>$(id).replaceChildren());$('more').hidden=true;$('save-status').textContent='Core projection unavailable: '+error.message;}
}
let visibleGroups=new Set(['Housing','Debt','Food','Shopping and home','Travel','AI','Insurance','Giving','Taxes','Digital services','Lifestyle','Transport','Health','Needs review','Business','Infrastructure','Other work']);
const groups=[...classificationGroups],colors=['var(--series1)','var(--series7)','var(--series2)','var(--series3)','var(--series4)','var(--series5)','var(--series6)','#c1a276','#798cc2','#b590b5','#70a8a5','#c58289','#939f68','#749db3','#bd9a67','#908bab','#8da89d','#969696'];
function element(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
function rows(all=false){return dashboardRows(data,overrides,{scope:localStorage.getItem('home-budget-overview-scope')||'combined',period:$('period').value,hideReimbursed:$('hide-reimbursed').checked,all})}
function overviewScopeRows(rr){return scopeRows(rr,localStorage.getItem('home-budget-overview-scope')||'combined',overrides.commitments||{})}function householdRows(){return overviewScopeRows(rows().filter(r=>r.scope==='Household'))}
function spending(){return householdRows().filter(r=>r.spend>0)}
function table(target,headers,entries){const tb=element('table'),head=element('thead'),tr=element('tr');headers.forEach((s,i)=>{const th=element('th',s);if(i)th.className='number';tr.append(th)});head.append(tr);tb.append(head);const body=element('tbody');entries.forEach(row=>{const tr=element('tr');row.forEach((v,i)=>{const td=element('td');if(v instanceof Node)td.append(v);else td.textContent=v;if(i)td.className='number';tr.append(td)});body.append(tr)});tb.append(body);$(target).replaceChildren(tb)}


function sourceCoverageStats(){return evidenceReport;}
let originalEraMonthlyCounts={};
function renderAccountSourceMonths(){
 const months=evidenceReport.months,raw=evidenceReport.rr;
 const accounts=[...new Set(raw.map(r=>r.account))].sort();
 const tb=element('table'),head=element('tr');head.append(element('th','Account'));months.forEach(m=>{const h=element('th',new Date(m+'-15T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'}));h.colSpan=3;head.append(h)});tb.append(head);
 const sub=element('tr');sub.append(element('th','Source records'));months.forEach(()=>['Era','Statement / export','Receipts linked'].forEach(x=>sub.append(element('th',x))));tb.append(sub);
  evidenceReport.accounts.forEach(account=>{const tr=element('tr');tr.append(element('td',account.account));account.monthly.forEach(cell=>[cell.era_original_count,cell.statement_count,cell.receipt_count].forEach(n=>{const td=element('td',n===null?'Unknown':String(n));td.className='number';tr.append(td)}));tb.append(tr)});
 const total=element('tr');total.append(element('th','Total records'));evidenceReport.totals.forEach(cell=>[cell.era_original_count,cell.statement_count,cell.receipt_count].forEach(n=>{const td=element('th',n===null?'Unknown':String(n));td.className='number';total.append(td)}));tb.append(total);
 $('account-source-months').replaceChildren(tb);const note=element('p','Era counts use preserved original feed metadata when available, account-wide for each displayed account. Unknown means the original feed inventory has not been loaded. Statement/export and receipt counts use unique ledger records in the selected Home/Work scope. The same purchase can appear in multiple columns; counts are not additive and unequal counts do not alone prove a gap. Receipt counts show transactions with supporting evidence. Zero means no records available here, not a confirmed inactive month.');note.className='small muted';$('account-source-months').append(note);
}

function renderSourceCoverage(){table('source-reconciliation',['Source / evidence','Observed records','Receipt links','Verified reconciliation'],evidenceReport.evidence_types.map(r=>[r.label,r.record_count,r.linked_count===null?'Not established':r.linked_count,r.reconciliation_status]));}

function renderPageHeroes(){
 if(!$('page-heroes')||!currentReport)return;
 const rr=rows(),sp=rr.filter(r=>r.scope==='Household'&&r.spend>0),months=$('period').value==='all'?data.months.length:1,total=reportMeasure('spending_commitment'),mixed=reportMeasure('unallocated_received'),pay=reportMeasure('payroll_received'),reimb=reportMeasure('reimbursement_received'),items=planningItems();
 const moneyCard=(label,value,note='Recorded selected-period spending')=>{const metric=typeof value==='object'?value:{period_total:value,recorded_average_per_selected_month:value/months};return [label,money(metric.recorded_average_per_selected_month)+'/mo',money(metric.period_total)+' period total · '+(metric.estimated_component>0?metric.status:note)]};
 let stats=[];
 if(activeTab==='overview'||activeTab==='cash'){stats=[moneyCard('💵 Payroll',currentReport.measures.payroll_received,mixed?'Mixed deposits require allocation review':'Recorded payroll'),moneyCard('↩️ Reimbursements received',currentReport.measures.reimbursement_received,'Received inflow'),moneyCard('🧾 Purchases and bills',currentReport.measures.spending_commitment,'Card repayments excluded')];}
 else if(activeTab==='categories'){const ranked=currentReport.series.filter(series=>series.dimensions.kind==='spending_commitment').sort((a,b)=>(b.average_recorded_monthly_share_percent||0)-(a.average_recorded_monthly_share_percent||0));stats=[moneyCard('All categories',currentReport.measures.spending_commitment),...ranked.slice(0,3).map(series=>moneyCard(series.dimensions.group,series,(series.average_recorded_monthly_share_percent||0).toFixed(1)+'% recorded monthly share'))];}
 else if(activeTab==='purpose'){stats=detailSeries(['kind','purpose']).map(series=>moneyCard(series.dimensions.purpose,series,'Recorded purpose; funding separate'));}
 else if(activeTab==='cards'){stats=[['💳 Reported card debt',accountReport?.reported_debt_total==null?'Unknown':money(accountReport.reported_debt_total),accountReport?.status||'Loading'],['Cards in view',String(accountReport?.account_count??0),'Period and reimbursement toggle do not change snapshots'],['Unresolved attribution',String(accountReport?.unresolved_account_count??0),'Account purpose/ownership needs review']];}
 else if(activeTab==='coverage'){renderSourceCoverage();renderAccountSourceMonths();stats=evidenceReport.summary.map(r=>[r.label,String(r.record_count),r.note]);}
 else if(activeTab==='transactions'){stats=transactionReport?[['Matching records',String(transactionReport.summary.record_count),'Shared query filters applied'],moneyCard('Matching spending',transactionReport.summary.spending),['Accounts',String(transactionReport.summary.account_count),'Represented in matching records']]:[['Matching records','Loading','Awaiting shared query']];}
 else if(activeTab==='budget'){const plan=allReport.budget_comparison;stats=[['🎯 Monthly targets',money(plan.monthly_target_total)+'/mo',plan.status],['Categories planned',String(plan.planned_category_count),'Unset categories still need a target'],moneyCard('Recorded spending',currentReport.measures.spending_commitment)];}
 else if(activeTab==='baseline'){const summary=planningReport?.scope_totals.find(r=>r.scope===$('baseline-mode').value);stats=summary?[['🧱 Selected baseline',money(summary.monthly_total)+'/mo',summary.selected_count+' selected essentials · saved planning decisions'],['Expected shared funding',money(summary.expected_contribution_offset)+'/mo','Expected arrangement; deposits not matched'],['To fund',money(summary.monthly_to_cover)+'/mo','Reimbursement income is not assumed']]:[];}
 else {const type=activeTab==='subscriptions'?'subscription':'bill',total=planningReport?.candidate_totals.find(r=>r.candidate_type===type);stats=total?[['📅 Monthly planning amount',money(total.scheduled_monthly_amount)+'/mo','Editable schedule assumptions · not a confirmed obligation'],['Items to review',String(total.item_count),'In selected home/work scope'],['Observed period',money(total.observed_period_total),'Gross recorded charges']]:[];}
 const host=$('page-heroes');host.replaceChildren();stats.forEach(([label,value,note])=>{const card=element('div');card.className='page-hero';const l=element('div',label);l.className='page-hero-label';const v=element('div',value);v.className='metric';const d=element('div',note);d.className='small muted';card.append(l,v,d);host.append(card)});
 if(activeTab==='cash'){
 const mode=localStorage.getItem('home-budget-overview-scope')||'combined',wife=reportMeasure('expected_contribution'),incoming=reportMeasure('incoming_with_expected_funding'),gap=reportMeasure('funding_less_spending');
 host.replaceChildren();const assessment=currentReport.funding_comparison,missingIncome=assessment.monthly_recorded_difference===null,banner=element('div');banner.className='cash-hero';const lead=element('div');lead.append(element('div',missingIncome?'INCOME EVIDENCE INCOMPLETE':'RECORDED FUNDING COMPARISON'));const value=element('div',missingIncome?'Not established':money(Math.abs(assessment.monthly_recorded_difference)));value.className='cash-hero-number';lead.append(value,element('div',missingIncome?'Income not established for: '+assessment.missing_income_evidence_months.join(', '):money(Math.abs(gap))+' '+(gap<0?'recorded purchases above funding':'recorded funding above purchases')+' over selected period'));const breakdown=element('div');breakdown.className='cash-hero-breakdown';[['Coming in',incoming,'Payroll + reimbursements + classified wife funding + remaining expected contributions'],['Spending',total,'Purchases and bills · card repayments excluded']].forEach(([label,n,note])=>{const box=element('div');box.append(element('div',label));const measure=label==='Coming in'?currentReport.measures.incoming_with_expected_funding:currentReport.measures.spending_commitment;const v=element('div',money(measure.recorded_average_per_selected_month)+'/mo');v.className='metric';box.append(v);const detail=element('div',note);detail.className='small muted';box.append(detail);breakdown.append(box)});banner.append(lead,breakdown);const foot=element('div',missingIncome?'Review source coverage before drawing a shortfall or surplus conclusion.':'Recorded funding and purchases are a comparison, not a spendable balance.');foot.className='cash-hero-foot';foot.append(element('div','Bank cash flow and debt growth are not reconciled here. Funding may include expected contributions and estimated allocations; card repayments are separate.'));banner.append(foot);host.append(banner);
 }

}

function openTab(tab){activeTab=tab;try{localStorage.setItem('home-budget-active-tab',tab)}catch(e){}['overview','categories','cash','purpose','commitments','budget','transactions','coverage','cards','baseline','subscriptions'].forEach(id=>$(id).hidden=id!==tab);document.querySelectorAll('[data-overview-scope]').forEach(b=>{b.classList.toggle('active',b.dataset.overviewScope===(localStorage.getItem('home-budget-overview-scope')||'combined'));b.onclick=()=>{localStorage.setItem('home-budget-overview-scope',b.dataset.overviewScope);$('baseline-mode').value=b.dataset.overviewScope;document.querySelectorAll('[data-overview-scope]').forEach(x=>x.classList.toggle('active',x===b));render()}});document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='overview')drawChart();renderPageHeroes()}
function link(text,fn){const b=element('button',text);b.className='rowlink';b.onclick=fn;return b}
function bar(target,label,value,max,color,isCategory=groups.includes(label)){const row=element('div');row.className='barrow';row.append(isCategory?link(label,()=>{groupSelected=label;openTab('categories');renderDetail()}):element('span',label));const track=element('div');track.className='track';const fill=element('div');fill.className='fill';fill.style.width=(max?value/max*100:0)+'%';if(color)fill.style.background=color;track.append(fill);row.append(track);const n=element('span',isCategory?short(reportSeries(currentReport,label)?.recorded_average_per_selected_month??0)+'/mo':short(value));n.style.textAlign='right';if(isCategory){const total=element('div',short(value)+' total');total.className='small muted';n.append(total)}row.append(n);$(target).append(row)}
const categoryColors=Object.fromEntries(groups.map((g,i)=>[g,colors[i]]));
function averageShare(group){return (reportSeries(allReport,group)?.average_recorded_monthly_share_percent||0)/100}
function renderContent(){$('show-tata-funding').onchange=render;renderPlanning();
 groups.sort((a,b)=>averageShare(b)-averageShare(a));
 const rr=householdRows(),sp=spending(),gross=reportMeasure('spending_commitment'),salary=reportMeasure('payroll_received'),work=reportMeasure('reimbursement_received');
 $('source-status').textContent=data.source_status+' · '+data.as_of+' · Select Transactions to curate classifications.';

 $('kpis').replaceChildren();$('outflow-kpis').replaceChildren();[['Payroll received',salary,referenceNote("reference_6")],['Purchases and bills',gross,'Gross spending · includes reimbursable work'],['Reimbursements received',work,referenceNote("reference_7")]].forEach(([label,n,note])=>{const p=element('div');p.className='panel';p.append(element('div',label));const measureKey=label==='Payroll received'?'payroll_received':label==='Reimbursements received'?'reimbursement_received':'spending_commitment';const v=element('div',money(currentReport.measures[measureKey].recorded_average_per_selected_month));v.className='metric';p.append(v);const avg=element('div','Monthly average');avg.className='small';p.append(avg);const total=element('div',money(n)+' selected-period total');total.className='small muted';p.append(total);const measure=label==='Payroll received'?currentReport.measures.payroll_received:label==='Reimbursements received'?currentReport.measures.reimbursement_received:null;const text=element('div',measure?.estimated_component>0?measure.status:note);text.className='small muted';p.append(text);$(label==='Purchases and bills'?'outflow-kpis':'kpis').append(p)});const wifePanel=element('div');wifePanel.className='panel';wifePanel.append(element('div','Wife contributions'));const wifeMonthly=currentReport.measures.expected_contribution.recorded_average_per_selected_month;const wifeValue=element('div',money(wifeMonthly));wifeValue.className='metric';wifePanel.append(wifeValue);const wifeLabel=element('div','Expected monthly contribution arrangement');wifeLabel.className='small';wifePanel.append(wifeLabel);const wifeMonths=$('period').value==='all'?data.months.length:1;const wifeTotal=element('div',money(currentReport.measures.expected_contribution.period_total)+' expected selected-period total');wifeTotal.className='small muted';wifePanel.append(wifeTotal);const wifeNote=element('div',referenceNote("reference_8"));wifeNote.className='small muted';wifePanel.append(wifeNote);$('kpis').append(wifePanel);const inflowMonths=$('period').value==='all'?data.months.length:1;const combinedInflow=reportMeasure('incoming_with_expected_funding');const inflowSummary=$('inflow-summary');inflowSummary.replaceChildren();const combinedAvg=element('div',money(currentReport.measures.incoming_with_expected_funding.recorded_average_per_selected_month)+' / month');combinedAvg.className='metric';inflowSummary.append(combinedAvg);const combinedTotal=element('div',money(combinedInflow)+' selected-period total');combinedTotal.className='small muted';inflowSummary.append(combinedTotal);const combinedNote=element('div','Recorded payroll + reimbursements received + classified wife funding + remaining expected contributions. Mixed-deposit allocations require review; wife deposits are not yet matched.');combinedNote.className='small muted';inflowSummary.append(combinedNote);
 $('legend').replaceChildren();groups.filter(g=>(reportSeries(currentReport,g)?.period_total??0)>0).forEach((g,i)=>{const s=element('button'),sw=element('span');s.setAttribute('aria-pressed',String(visibleGroups.has(g)));s.style.opacity=visibleGroups.has(g)?'1':'.45';sw.className='swatch';sw.style.background=categoryColors[g];const mm=$('period').value==='all'?data.months:[$('period').value];const avgShare=reportSeries(chartReport,g)?.average_recorded_monthly_share_percent??0;s.append(sw,document.createTextNode(g+' · '+(visibleGroups.has(g)?avgShare.toFixed(1)+'% avg':'off')));s.onclick=()=>{if(visibleGroups.has(g))visibleGroups.delete(g);else visibleGroups.add(g);render()};$('legend').append(s)});
 const amounts=groups.map(g=>reportSeries(currentReport,g)?.period_total??0);$('big-categories').replaceChildren();groups.map((g,i)=>({g,i,n:amounts[i]})).sort((a,b)=>averageShare(b.g)-averageShare(a.g)).filter(o=>o.n>0).slice(0,8).forEach(o=>bar('big-categories',o.g,o.n,Math.max(...amounts),categoryColors[o.g]));
 const all=overviewScopeRows(rows(true).filter(r=>r.scope==='Household'&&r.spend>0));const columns=data.months.map(m=>m.slice(5)==='07'?'July':m.slice(5)==='08'?'August':'September');
 table('category-table',['Category',...columns,'Verified min','Verified max','Recorded average','Recorded share'],groups.map(g=>{const series=reportSeries(allReport,g);return [link(g,()=>{groupSelected=g;renderDetail()}),...data.months.map(m=>{const n=series?.monthly.find(r=>r.month===m)?.recorded_total;return n==null?'—':money(n)}),'Not certified','Not certified',series?money(series.recorded_average_per_selected_month):'—',series?.average_recorded_monthly_share_percent==null?'—':series.average_recorded_monthly_share_percent.toFixed(1)+'%']}));renderDetail();
 const cashKinds=[['Payroll','payroll_received'],['Curated earned income','earned_income_received'],['Estimated payroll allocation · matching not certified','estimated_payroll_allocation'],['Reimbursements received','reimbursement_received'],['Estimated reimbursement allocation · matching not certified','estimated_reimbursement_allocation'],['Mixed deposits — allocation pending','mixed_business_inflow'],['Outside inflows — review','unclassified_inflow'],['Classified wife funding','wife_funding_received'],['Refunds / rewards','refund_recorded'],['Direct bank-paid bills · subset of purchases','spending_commitment','bank'],['Card repayments · separate settlement','card_settlement'],['Internal transfers · excluded from income','internal_transfer']];
 if($('show-tata-funding').checked)cashKinds.push(['Tata joint-account funding · excluded from income','informational_funding']);
 table('cash-table',['Movement',...columns],cashKinds.map(([label,kind,channel])=>{const report=cashReports.find(r=>r.dimensions.length===(channel?2:1)),series=report?.series.find(r=>r.dimensions.kind===kind&&(!channel||r.dimensions.payment_channel===channel));return [label,...data.months.map(month=>{const value=series?.monthly.find(cell=>cell.month===month)?.recorded_total;return value==null?'—':money(value)})]}));

 $('inflow-review').replaceChildren();rr.filter(r=>r.work_receipt||r.review_credit).forEach(r=>{const p=element('p');p.append(link(r.date+' · '+r.merchant+' · '+money(r.amount),()=>{openTab('transactions');edit(r.id)}));if(r.inflow_role)p.append(document.createTextNode(' · '+r.inflow_role));$('inflow-review').append(p)});
 $('purpose-bars').replaceChildren();detailSeries(['kind','purpose']).forEach(series=>bar('purpose-bars',series.dimensions.purpose,series.period_total,gross,undefined,false));
 table('wife-plan',['Bill','Expected/month'],currentReport.contribution_plan.items.map(item=>[item.bill,money(item.monthly_amount)]).concat([['Total',currentReport.contribution_plan.monthly_total===null?'Unknown':money(currentReport.contribution_plan.monthly_total)]]));
 $('funding-summary').replaceChildren(element('p','Classified wife receipts in selected period: '+money(currentReport.measures.wife_funding_received.period_total)),element('p',currentReport.contribution_plan.status),element('p','Matched reimbursement amount: not established'),element('p','Shared spending on your accounts: '+money(detailSeries(['kind','purpose']).find(series=>series.dimensions.purpose==='Household')?.period_total??0)));

 sourceInspector.refresh();renderAccounts();renderCommitments();renderBudget();renderTransactions();table('coverage-table',['Account','July records','August records','September records','Source status'],data.coverage.map(a=>[a.name,...data.months.map(m=>a.months[m]),a.status]));drawChart();renderPageHeroes();
}
function merchantTable(series,total){
 const mm=currentReport.months,target=element('div');target.className='scroll';const tb=element('table'),head=element('tr');
 ['Place / merchant',...mm.map(m=>new Date(m+'-15').toLocaleString('en-US',{month:'short',year:'numeric'})),'Total','Source references'].forEach((label,i)=>{const th=element('th',label);if(i)th.className='number';head.append(th)});tb.append(head);
 [...series].sort((a,b)=>b.period_total-a.period_total).forEach(item=>{
  const tr=element('tr'),td=element('td');td.append(link(item.dimensions.merchant||'Merchant not recorded',()=>{openTab('transactions');$('search').value='';renderTransactionsForBills(new Set(item.transaction_ids))}));tr.append(td);
  [...mm.map(month=>item.monthly.find(r=>r.month===month)?.recorded_total),item.period_total].forEach(amount=>{const cell=element('td',amount==null?'—':money(amount));cell.className='number';tr.append(cell)});
  const evidence=element('td',String(item.source_refs.length));evidence.className='number';evidence.title='Immutable source references; this count does not certify coverage';tr.append(evidence);tb.append(tr);
 });
 const footer=element('tr');footer.append(element('th','Recorded total'));
 [...mm.map(month=>total?.monthly.find(r=>r.month===month)?.recorded_total),total?.period_total].forEach(amount=>{const cell=element('th',amount==null?'—':money(amount));cell.className='number';footer.append(cell)});footer.append(element('th',String(total?.source_refs.length||0)));tb.append(footer);target.append(tb);return target;
}
function renderDetail(){
 if(!currentReport)return;
 const filters={group:groupSelected},total=reportSeries(currentReport,groupSelected),travel=groupSelected==='Travel',dimension=travel?'travel_purpose':'category';
 $('category-title').textContent=groupSelected+' · '+(total?money(total.period_total):'No recorded spending');
 $('category-detail').replaceChildren(element('h3','All places purchased'),merchantTable(detailSeries(['kind','group','merchant'],filters),total),element('h3',travel?'Break down by travel purpose':'Break down by subcategory'));
 const categories=detailSeries(['kind','group',dimension],filters).sort((a,b)=>b.period_total-a.period_total);
 categories.forEach(category=>{
  const value=category.dimensions[dimension],categoryFilters={...filters,[dimension]:value},details=element('details');details.append(element('summary',(value||'Unclassified')+' · '+money(category.period_total)),merchantTable(detailSeries(['kind','group',dimension,'merchant'],categoryFilters),category));
  if(groupSelected==='Food'&&value==='Eating out')detailSeries(['kind','group','category','detail'],categoryFilters).forEach(part=>{
   const child=element('details');child.append(element('summary',(part.dimensions.detail||'Detail not recorded')+' · '+money(part.period_total)),merchantTable(detailSeries(['kind','group','category','detail','merchant'],{...categoryFilters,detail:part.dimensions.detail}),part));details.append(child);
  });
  $('category-detail').append(details);
 });givingTrail();
}

function givingTrail(){const g=evidenceReport?.giving_trail;if(!g||groupSelected!=='Giving')return;const d=element('details');d.open=true;d.append(element('summary','Giving evidence · '+g.receipt_count+' attributed receipts · '+money(g.observed_receipt_total)));d.append(element('p',g.status+' '+g.context_custody_status));const tb=element('table'),head=element('tr');['Gift date','Fund','Observed amount','Attribution / reconciliation'].forEach(h=>head.append(element('th',h)));tb.append(head);[...g.receipts,...g.unresolved_receipts].forEach(r=>{const tr=element('tr');[r.date,r.fund,Number.isFinite(r.amount)?money(r.amount):'Unknown',r.attribution_status+' · '+r.reconciliation_status].forEach(v=>tr.append(element('td',v)));tb.append(tr)});const wrap=element('div');wrap.className='scroll';wrap.append(tb);d.append(wrap);d.append(element('p',g.unresolved_receipt_count+' unresolved receipts excluded from attributed total. '+g.funding_candidate_count+' funding-transfer candidates in this view; these are not additional gifts.'));const ft=element('table'),fh=element('tr');['Funding date','Reported amount','Source account','Attribution / evidence'].forEach(h=>fh.append(element('th',h)));ft.append(fh);g.funding_candidates.forEach(r=>{const tr=element('tr');[r.funding_date,Number.isFinite(r.funding_amount)?money(r.funding_amount):'Unknown',r.source_account,r.attribution_status+' · '+r.reconciliation_status].forEach(v=>tr.append(element('td',v)));ft.append(tr)});d.append(ft);$('category-detail').append(d)}
function drawChart(){const svg=$('chart'),width=Math.max(300,svg.clientWidth),height=300,pad=64,right=15,top=30,bottom=45;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.replaceChildren();const mm=$('period').value==='all'?data.months:[$('period').value];if(!chartReport)return;const vals=mm.map(m=>groups.map(g=>reportSeries(chartReport,g)?.monthly.find(r=>r.month===m)?.recorded_total??0)),monthTotals=mm.map(month=>chartReport.monthly_kind_totals.find(r=>r.kind==='spending_commitment'&&r.month===month)?.recorded_total??null),max=Math.max(1,...monthTotals.map(n=>n??0))*1.12;const ns='http://www.w3.org/2000/svg';function shape(tag,attrs,text){const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;svg.append(e);return e}for(let i=0;i<=4;i++){const value=max*i/4,y=height-bottom-(height-top-bottom)*i/4;shape('line',{x1:pad,y1:y,x2:width-right,y2:y});shape('text',{x:pad-8,y:y+4,'text-anchor':'end'},short(value))}const step=(width-pad-right)/mm.length;mm.forEach((m,j)=>{const bw=Math.min(95,step*.6),x=pad+j*step+(step-bw)/2;let y=height-bottom;vals[j].forEach((v,i)=>{if(v<=0)return;const h=v/max*(height-top-bottom);y-=h;const rect=shape('rect',{x,y,width:bw,height:h,fill:categoryColors[groups[i]]});const title=document.createElementNS(ns,'title');title.textContent=groups[i]+' '+money(v);rect.append(title);const monthTotal=monthTotals[j];if(h>=19&&bw>=50&&v>0){const label=shape('text',{x:x+bw/2,y:y+h/2+4,'text-anchor':'middle'},(reportSeries(chartReport,groups[i])?.monthly.find(r=>r.month===m)?.recorded_share_percent??0).toFixed(0)+'%');label.style.fill='var(--text)'}});shape('text',{x:x+bw/2,y:y-8,'text-anchor':'middle'},monthTotals[j]===null?'—':short(monthTotals[j]));shape('text',{x:x+bw/2,y:height-22,'text-anchor':'middle'},m==='2026-07'?'July':m==='2026-08'?'August':m==='2026-06'?'June':'September')});shape('text',{x:pad,y:15},visibleGroups.size===groups.length?'Gross expenses (USD)':'Visible categories (USD)')}
function renderAccounts(){if(!accountReport)return;$('card-snapshot-summary').textContent=accountReport.reported_debt_total===null?'No classified snapshots available':money(accountReport.reported_debt_total)+' reported debt';$('card-snapshot-status').textContent=accountReport.status+' · '+(accountReport.mixed_dates?'Mixed balance dates: ':'Balance date: ')+(accountReport.oldest_as_of||'Unknown')+(accountReport.mixed_dates?' through '+accountReport.newest_as_of:'');table('card-snapshot-table',['Card','Institution','Reported balance','Balance as of','Attribution','Source observation'],accountReport.items.map(row=>[row.account,row.institution,money(row.balance),row.as_of,row.ownership_status,row.source_refs?.length?row.source_refs.map(ref=>ref.source_type+' · '+ref.observed_at).join('; '):'Source reference unavailable']));}
function renderCommitments(){
 if(!planningReport)return;
 const items=planningReport.items.filter(item=>item.bill_candidate),tb=element('table'),head=element('tr');['Bill / service','Schedule evidence',...planningReport.months.map(month=>new Date(month+'-15').toLocaleString('en-US',{month:'short'})),'Recorded avg/mo','Planned/month','Decision'].forEach(label=>head.append(element('th',label)));tb.append(head);
 [...items].sort((a,b)=>b.period_total-a.period_total).forEach(item=>{
  const tr=element('tr'),name=element('td');name.append(link(item.name,()=>{openTab('transactions');renderTransactionsForBills(new Set(item.transaction_ids))}));tr.append(name,element('td',item.schedule_status));
  [...item.monthly.map(r=>r.recorded_total),item.recorded_average_per_selected_month].forEach(amount=>{const cell=element('td',amount==null?'—':money(amount));cell.className='number';tr.append(cell)});
  const target=element('input');target.type='number';target.min='0';target.step='.01';target.placeholder='Confirm';target.value=item.planned_monthly_target??'';target.setAttribute('aria-label',item.name+' planned monthly commitment');const targetCell=element('td');targetCell.append(target);tr.append(targetCell);
  const choice=element('select');['Review','Keep','Business','Consider cutting'].forEach(value=>choice.add(new Option(value,value)));choice.value=item.decision;
  const update=async()=>{const old=overrides.commitments[item.name];overrides.commitments[item.name]={...commitmentDecision(old),decision:choice.value,target:target.value===''?null:Number(target.value)};if(await save())await render();};target.onchange=update;choice.onchange=update;const cell=element('td');cell.append(choice);tr.append(cell);tb.append(tr);
 });$('commitment-table').replaceChildren(tb);const totals=planningReport.candidate_totals.find(r=>r.candidate_type==='bill');$('commitment-summary').textContent=totals.item_count+' bills/services to review · Saved planning targets: '+money(totals.planned_monthly_target)+'/month · Consider-cutting items: '+money(totals.consider_cutting_recorded_average)+'/month recorded spending (not guaranteed savings).';
}

function planningItems(){return sharedPlanningItems(rows(true),data.months)}
function billingControl(item){
 const box=element('div'),frequency=element('select');['Unconfirmed','Monthly','Annual','One-time'].forEach(value=>frequency.add(new Option(value,value)));frequency.value=item.billing_frequency;frequency.setAttribute('aria-label',item.name+' billing frequency');
 const charge=element('input');charge.type='number';charge.min=0;charge.step='.01';charge.value=item.billing_charge;charge.setAttribute('aria-label',item.name+' amount per billing cycle');charge.style.width='100px';
 const update=async()=>{const old=overrides.commitments[item.name]||{};overrides.commitments[item.name]={...commitmentDecision(old),billingFrequency:frequency.value,billingCharge:Number(charge.value)};if(await save())await render();};frequency.onchange=update;charge.onchange=update;box.append(frequency,charge,element('div',item.schedule_status));if(item.billing_frequency==='Annual')box.append(element('div',money(item.scheduled_monthly_amount)+'/month reserve'));return box;
}
function renderPlanning(){
 if(!planningReport)return;
 const mode=$('baseline-mode').value,items=planningReport.items,summary=planningReport.scope_totals.find(r=>r.scope===mode),tb=element('table'),head=element('tr');['Non-negotiable / budget','Item','Amount evidence','Billing schedule','Baseline/month'].forEach(label=>head.append(element('th',label)));tb.append(head);
 [...items].sort((a,b)=>b.recorded_average_per_selected_month-a.recorded_average_per_selected_month).forEach(item=>{
  const work=item.assigned_scope==='work',tr=element('tr'),choiceCell=element('td'),check=element('input');check.type='checkbox';check.checked=item.essential;check.setAttribute('aria-label',item.name+' non-negotiable');choiceCell.append(check);
  const move=element('button',work?'Move to Home':'Move to Work');move.className='small';move.setAttribute('aria-label',item.name+(work?' move to Home':' move to Work'));move.style.marginLeft='10px';move.onclick=async()=>{overrides.commitments[item.name]={...commitmentDecision(overrides.commitments[item.name]),budgetScope:work?'home':'work',[work?'essential':'workEssential']:check.checked,[work?'baselineAmount':'workBaselineAmount']:Number(amount.value)};if(await save())await render();};choiceCell.append(move);
  tr.append(choiceCell,element('td',item.name),element('td',item.observed_month_count===item.evidence_month_count?money(item.recorded_average_per_selected_month)+' recorded monthly average':money(item.latest_charge)+' latest charge · '+item.observed_month_count+' of '+item.evidence_month_count+' months present'));
  const schedule=element('td');schedule.append(billingControl(item));tr.append(schedule);const amount=element('input');amount.type='number';amount.min=0;amount.step='.01';amount.value=item.baseline_monthly_amount;amount.setAttribute('aria-label',item.name+' baseline monthly amount');const amountCell=element('td');amountCell.append(amount);tr.append(amountCell);
  const update=async()=>{const latest=commitmentDecision(overrides.commitments[item.name]),currentWork=latest.budgetScope?latest.budgetScope==='work':work;overrides.commitments[item.name]={...latest,[currentWork?'workEssential':'essential']:check.checked,[currentWork?'workBaselineAmount':'baselineAmount']:Number(amount.value)};if(await save())await render();};check.onchange=update;amount.onchange=update;tb.append(tr);
 });$('baseline-table').replaceChildren(tb);
 $('baseline-summary').textContent=summary.selected_count+' selected essentials · '+money(summary.monthly_total)+'/month '+mode+' baseline · '+summary.status;
 const heroes=$('baseline-category-heroes');heroes.replaceChildren();const grand=element('div');grand.className='panel';grand.style.background='var(--soft)';grand.style.gridColumn='1/-1';grand.append(element('h2',mode.charAt(0).toUpperCase()+mode.slice(1)+' budget · grand total'));const number=element('div',money(summary.monthly_total)+' / month');number.className='metric';grand.append(number,element('div',summary.selected_count+' selected essentials · planned monthly amounts'));
 if(mode!=='work'){grand.append(element('p','Expected wife contribution toward selected bills: '+money(summary.expected_contribution_offset)+' / month'));const net=element('div',money(summary.monthly_to_cover)+' / month for you to cover');net.className='metric';grand.append(net,element('p','Expected funding arrangement; actual deposits still need reconciliation.'));}heroes.append(grand);
 summary.categories.forEach(category=>{const card=element('div');card.className='panel';card.style.borderTop='4px solid '+(categoryColors[category.category]||'var(--accent)');const value=element('div',money(category.monthly_amount));value.className='metric';card.append(element('h3',category.category),value,element('div','per month · selected essentials'));heroes.append(card)});
 const sort=$('subscription-sort').value,subscriptions=items.filter(item=>item.subscription_candidate).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='decision'?a.decision.localeCompare(b.decision)||b.scheduled_monthly_amount-a.scheduled_monthly_amount:b.scheduled_monthly_amount-a.scheduled_monthly_amount),st=element('table'),sh=element('tr');['Service','Purpose','Recorded avg/month','Evidence','Billing schedule','Decision'].forEach(label=>sh.append(element('th',label)));st.append(sh);
 subscriptions.forEach(item=>{const tr=element('tr'),name=element('td');name.append(link(item.name,()=>{openTab('transactions');renderTransactionsForBills(new Set(item.transaction_ids))}));tr.append(name,element('td',item.assigned_scope==='work'?'Work / reimbursement review':'Home / purpose review'),element('td',money(item.recorded_average_per_selected_month)),element('td',item.observed_month_count+' of '+item.evidence_month_count+' months observed; '+item.source_refs.length+' immutable source references'));
 const schedule=element('td');schedule.append(billingControl(item));tr.append(schedule);const choice=element('select');['Review','Keep','Business','Consider cutting'].forEach(value=>choice.add(new Option(value,value)));choice.value=item.decision;choice.setAttribute('aria-label',item.name+' subscription decision');choice.onchange=async()=>{const old=overrides.commitments[item.name];overrides.commitments[item.name]={...commitmentDecision(old),decision:choice.value};if(await save())await render();};const cell=element('td');cell.append(choice);tr.append(cell);st.append(tr);
 });$('subscription-table').replaceChildren(st);
 const host=$('subscription-summary');host.replaceChildren(element('div',subscriptions.length+' services / usage candidates · gross recorded billing evidence'));const grid=element('div');grid.className='kpis';grid.style.gridTemplateColumns='repeat(auto-fit,minmax(180px,1fr))';
 planningReport.subscription_decision_totals.forEach(total=>{const card=element('div');card.className='panel';const amount=element('div',money(total.scheduled_monthly_amount)+'/month');amount.className='metric';card.append(element('h3',total.decision),amount,element('div',money(total.observed_period_total)+' observed period total · '+total.item_count+' services'),element('div',total.status));grid.append(card)});host.append(grid);renderPageHeroes();
}

function renderTransactionsForBills(ids){recordSelection=[...ids];limit=Math.max(60,ids.size);renderTransactions();}
function renderBudget(){const plan=allReport.budget_comparison,tb=element('table'),tr=element('tr');['Category','Recorded avg/month','Our target/month'].forEach(h=>tr.append(element('th',h)));tb.append(tr);plan.items.forEach(item=>{const tr=element('tr');tr.append(element('td',item.category),element('td',item.recorded_average_per_selected_month===null?'—':money(item.recorded_average_per_selected_month)));const td=element('td'),inp=element('input');inp.type='number';inp.min='0';inp.step='.01';inp.placeholder='Undecided';inp.value=item.monthly_target??'';inp.onchange=async()=>{if(inp.value==='')delete overrides.budgets[item.category];else overrides.budgets[item.category]=Number(inp.value);if(await save())await render()};td.append(inp);tr.append(td);tb.append(tr)});$('budget-table').replaceChildren(tb);$('budget-summary').textContent='Targets set: '+plan.planned_category_count+'/'+plan.category_count+' · Planned spending '+money(plan.monthly_target_total)+'/month · Payroll funding '+money(plan.payroll_funding_monthly)+'/month · Payroll less targets '+money(plan.payroll_less_targets)+'. '+(plan.payroll_estimated_monthly>0?plan.payroll_status+'. ':'')+plan.status;if(document.activeElement!==$('notes'))$('notes').value=overrides.notes||'';renderPageHeroes()}

async function renderTransactions(){
 const sequence=++transactionRequest,revision=data._revision,scope=localStorage.getItem('home-budget-overview-scope')||'combined',selection=recordSelection;
 const args={collection:'records',scope,period:selection?'all':$('period').value,hide_reimbursed:$('hide-reimbursed').checked,...(selection?{record_ids:selection}:{search:$('search').value,account:$('account-filter').value,purpose:$('purpose-filter').value})};
 transactionReport=null;try{
  let rr=[],response,offset=0;
  do{const res=await fetch('/api/capability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'query',args:{...args,offset,limit:Math.min(200,limit-rr.length)}})});response=await res.json();if(sequence!==transactionRequest)return;if(!res.ok)throw Error(response.error||'Record query failed');if(response.revision!==revision||response.revision!==data._revision)throw Error('Source revision changed; reload before continuing');rr.push(...response.items);offset=response.next_offset;}while(offset!==null&&rr.length<limit);
  if(sequence!==transactionRequest)return;transactionReport=response;$('transaction-count').textContent=response.total+' transactions · showing '+rr.length;
  table('transaction-table',['Date / merchant','Account','Amount','Category / purpose','Source'],rr.map(r=>{const label=element('div');label.className='transaction-name';label.append(element('div',r.date),link(r.merchant,()=>edit(r.id)));const info=element('div',r.category+' · '+r.purpose);if(r.group==='Travel')info.append(element('div',(r.travel_purpose||'Unclassified')+' travel'));return[label,r.account,money(r.amount),info,recordSourceNode(r.source_evidence)]}));
  $('more').hidden=response.total<=rr.length;renderPageHeroes();
 }catch(error){if(sequence!==transactionRequest)return;$('transaction-table').replaceChildren();$('transaction-count').textContent='Shared query unavailable: '+error.message;$('more').hidden=true;renderPageHeroes();}
}

function edit(id){const r=rows(true).find(r=>r.id===id);if(!r)return;const box=$('editor');box.hidden=false;box.replaceChildren(element('h3',r.date+' · '+r.merchant+' · '+money(r.amount)));function field(label,value,opts){const wrap=element('label',label),input=opts?element('select'):element('input');if(opts)opts.forEach(o=>input.append(new Option(o,o)));input.value=value||'';wrap.append(input);box.append(wrap);return input}const purpose=field('Purpose',r.purpose,['Household','Personal','Business','Unresolved']),group=field('Group',r.group,groups),category=field('Subcategory',r.category),role=field('Inflow classification',r.inflow_role||'Unresolved',['Unresolved','Wife contribution','Reimbursement','Earned income','Internal transfer','Other']);const travel=field('Travel purpose',r.travel_purpose||'Unclassified',['Unclassified','Work','Personal / family']);const insurance=field('Insurance type',r.insurance_type||'Unclassified',['Unclassified','Car','Health','Life','Disability','Pet','Home / renters','Other']);const note=field('Evidence / note',r.evidence);const saveButton=element('button','Save classification');saveButton.className='primary';saveButton.onclick=async()=>{overrides.transactions[id]={...(overrides.transactions[id]||{}),purpose:travel.value==='Work'&&group.value==='Travel'?'Business':purpose.value,travel_purpose:travel.value,group:group.value,insurance_type:insurance.value,category:group.value==='Insurance'&&insurance.value!=='Unclassified'?insurance.value+' insurance':category.value,evidence:note.value,inflow_role:role.value==='Unresolved'?'':role.value};if(await save()){render();box.hidden=true}};const sourceEvidence=element('div');recordSourceReader.show(sourceEvidence,r);const close=element('button','Close');close.onclick=()=>{recordSourceReader.invalidate();box.hidden=true};box.append(sourceEvidence,element('p','Original imported amount is preserved.'),saveButton,close);box.scrollIntoView({behavior:'smooth',block:'center'})}
const queuedSave=createSaveQueue(async document=>{
 const revision=data._revision,res=await fetch('/api/overrides',{method:'POST',headers:{'Content-Type':'application/json','If-Match':String(revision)},body:JSON.stringify(document)});
 if(res.status===409)return {ok:false,reason:'Another user saved changes. Export your edits, then reload before saving again.'};
 if(!res.ok)throw Error('Shared save failed. Changes remain unsaved; export edits before closing.');
 const result=await res.json();if(!Number.isInteger(result.revision)||result.revision!==revision+1)throw Error('Save revision not confirmed. Export edits and reload before retrying.');
 confirmedDecisions=structuredClone(document);data._revision=result.revision;recordSourceReader.invalidate();sourceInspector.clear();sourceInspector.refresh();++transactionRequest;transactionReport=null;return {ok:true,document};
});
function updateDraftRecovery(){const button=$('discard-draft');button.hidden=!hasUnsavedChanges();button.disabled=queuedSave.pending>0;}
async function save(){const pending=queuedSave(overrides);updateDraftRecovery();const result=await pending;updateDraftRecovery();if(!result.ok){$('save-status').textContent=result.reason;return false;}const current=JSON.stringify(overrides)===JSON.stringify(result.document);$('save-status').textContent=current?'Shared edits saved '+new Date().toLocaleTimeString():'Earlier edits saved; newer draft remains pending.';return current;}

async function load(options={}){try{await loadWithSaveGuard(queuedSave,{draft:()=>overrides,hasUnsavedChanges,discardDraft:options.discardDraft===true,read:async()=>{const res=await fetch('/api/data',{cache:'no-store'});if(!res.ok)throw Error('Protected data could not load. Refresh or sign in again.');return res.json();},apply:snapshot=>{recordSourceReader.invalidate();++transactionRequest;transactionReport=null;data=snapshot;overrides=data.overrides;confirmedDecisions=structuredClone(overrides);if(options.discardDraft===true){$('editor').hidden=true;$('editor').replaceChildren();}}});originalEraMonthlyCounts=data.original_era_monthly_counts||{};document.querySelectorAll("[data-reference-note]").forEach(e=>e.textContent=referenceNote(e.dataset.referenceNote));$('save-status').textContent='Source data loaded';updateDraftRecovery()}catch(e){$('save-status').textContent=e.message;updateDraftRecovery();return}$('account-filter').replaceChildren(new Option('All accounts',''));[...new Set(data.transactions.map(r=>r.account))].sort().forEach(a=>$('account-filter').append(new Option(a,a)));render()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openTab(b.dataset.open));$('baseline-mode').onchange=()=>{localStorage.setItem('home-budget-overview-scope',$('baseline-mode').value);render()};$('subscription-sort').onchange=renderPlanning;$('hide-reimbursed').onchange=()=>render();$('period').onchange=()=>{recordSelection=null;limit=60;render()};['search','account-filter','purpose-filter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{recordSelection=null;limit=60;renderTransactions()}));$('more').onclick=()=>{limit+=60;renderTransactions()};$('reload').onclick=load;$('discard-draft').onclick=()=>load({discardDraft:true});$('save-notes').onclick=async()=>{overrides.notes=$('notes').value;await save()};$('export').onclick=()=>{const blob=new Blob([JSON.stringify(overrides,null,2)],{type:'application/json'}),a=element('a');a.href=URL.createObjectURL(blob);a.download='home-budget-edits.json';a.click();URL.revokeObjectURL(a.href)};new ResizeObserver(()=>{if(activeTab==='overview')drawChart()}).observe($('chart'));try{const savedTab=localStorage.getItem('home-budget-active-tab');if(savedTab&&document.querySelector('[data-tab="'+savedTab+'"]'))openTab(savedTab)}catch(e){}openTab(activeTab);load();

const phoneMenu=document.querySelector('.phone-menu');phoneMenu.onclick=()=>{const open=document.querySelector('.cook-sidebar').classList.toggle('mobile-open');phoneMenu.setAttribute('aria-expanded',String(open));phoneMenu.textContent=open?'Close menu':'Menu';};document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.cook-sidebar').classList.remove('mobile-open');phoneMenu.setAttribute('aria-expanded','false');phoneMenu.textContent='Menu';}));
if('serviceWorker' in navigator&&['budget.klappy.dev','dev.budget.klappy.dev'].includes(location.hostname))navigator.serviceWorker.register('/service-worker.js').catch(()=>{});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.getElementById('install-app').hidden=false;});document.getElementById('install-app').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;document.getElementById('install-app').hidden=true;}};

}
