export function sum(rr,key){return rr.reduce((s,r)=>s+(Number(r[key])||0),0)}
export function purchasePlace(r){const s=r.merchant.toLowerCase();const rules=[[/toho\s*water|city\s*of\s*st[. ]*cloud/,'Water / sewer / trash'],[/wal.?mart/,'Walmart'],[/publix/,'Publix'],[/burger king/,'Burger King'],[/pei.?wei/,'Pei Wei'],[/starbucks/,'Starbucks'],[/atlas.?coffee/,'Atlas Coffee Club'],[/cielito/,'Cielito Coffee'],[/home.?depot/,'Home Depot'],[/coconuts/,'Coconuts'],[/doordash/,'DoorDash']];return rules.find(([p])=>p.test(s))?.[1]||r.merchant}
export function billName(r){if(r.subscription_name)return r.subscription_name;if(r.parent_transaction_id)return r.merchant;const s=(r.merchant+' '+r.description).toLowerCase();const rules=[[/insperity/,'Insperity'],[/mission orlando/,'Mission Orlando'],[/compassion/,'Compassion'],[/partnershipfca/,'FCA'],[/northwestern/,'Northwestern Mutual'],[/health plans/,'Health Plans'],[/progressive/,'Progressive'],[/lemonade/,'Lemonade'],[/sofi/,'SoFi loan'],[/greystar/,'Greystar settlement'],[/kua|kissimmee util/,'KUA electricity'],[/toho\s*water|city\s*of\s*st[. ]*cloud/,'Water / sewer / trash'],[/t.mobile/,'T-Mobile'],[/spectrum/,'Spectrum'],[/cursor/,'Cursor'],[/openai/,'OpenAI'],[/anthropic/,'Anthropic'],[/lovable/,'Lovable'],[/cloudflare/,'Cloudflare'],[/elevenlabs/,'ElevenLabs'],[/github/,'GitHub'],[/google|youtube/,'Google / YouTube — products to split'],[/apple.com|apple services/,'Apple services — products to split'],[/netflix/,'Netflix'],[/hulu/,'Hulu'],[/audible/,'Audible'],[/prime video/,'Prime Video'],[/ring/,'Ring'],[/nest/,'Nest'],[/experian/,'Experian'],[/remarkable/,'reMarkable'],[/cookidoo/,'Cookidoo'],[/dashpass/,'DoorDash DashPass'],[/rocket money/,'Rocket Money'],[/manychat/,'ManyChat'],[/massive/,'Massive'],[/fyxer/,'Fyxer'],[/replicate/,'Replicate'],[/twilio/,'Twilio']];if(r.group==='Insurance'&&/northwestern/i.test(s))return 'Northwestern Mutual · '+r.category;if(r.group==='Insurance'&&/lemonade/i.test(s))return 'Lemonade · pet insurance';if(r.category==='Tithe')return 'Mission Orlando';if(r.category==='Kingdom Builder offering')return 'Mission Orlando · Kingdom Builder offering';if(r.category==='Mortgage')return 'Mortgage';if(/interest/i.test(r.category)||r.source_type==='Interest')return 'Card interest · '+r.account;return rules.find(([p])=>p.test(s))?.[1]||r.merchant}
export function scopeRows(rows, scope='combined', commitments={}) {
 if(!['home','work','combined'].includes(scope))throw Error('Invalid scope');
 return rows.filter(r=>{const assigned=commitments[billName(r)]?.budgetScope;const work=assigned?assigned==='work':r.purpose==='Business'||r.work_receipt>0||r.inflow_role==='Mixed business income / reimbursement';return scope==='combined'||(scope==='work'?work:!work)});
}
export function dashboardRows(data, overrides={}, options={}) {
 const scope=options.scope||'combined', period=options.period||'all', months=data.months||[];
 let rows=data.transactions.flatMap(r=>{const parent={...r,...(overrides.transactions?.[r.id]||{})};return parent.splits?parent.splits.map(part=>({...parent,...part,splits:undefined,...(overrides.transactions?.[part.id]||{})})): [parent]});
 rows=scopeRows(rows,scope,overrides.commitments||{});
 return rows.map(r=>(r.group==='Travel'&&(r.travel_purpose==='Work'||['Paid','Submitted','Draft','Eligible','Reimbursable'].includes(r.reimbursement_status)))?{...r,purpose:'Business',travel_purpose:'Work'}:r)
 .map(r=>r.purpose==='Business'?{...r,original_group:r.group,group:'Business',category:r.group==='AI'?'AI · '+r.category:r.group==='Travel'?'Work travel · '+r.category:r.category}:r)
 .map(r=>{if(scope==='work'&&r.group==='Business'){const text=(r.merchant+' '+r.description+' '+r.category).toLowerCase();return {...r,group:r.original_group==='AI'||/anthropic|cursor|open\s*ai|claude|fyxer|elevenlabs|lovable|grok|replicate/.test(text)?'AI':r.original_group==='Travel'?'Travel':/cloudflare|github|twilio|hosting|domain/.test(text)?'Infrastructure':'Other work'}}return r})
 .map(r=>options.hideReimbursed&&r.reimbursement_status==='Paid'?{...r,spend:Math.max(0,r.spend-(r.reimbursement_amount||0))}:r)
 .filter(r=>options.all||period==='all'?months.includes(r.month):r.month===period);
}
export function planningItems(rows, months) {
 const bills={}; rows.filter(r=>r.scope==='Household'&&r.spend>0&&(['Housing','Debt','Insurance','Giving','Digital services','AI','Business'].includes(r.group)||r.category==='Groceries'||(r.group==='Food'&&/eating out|restaurant|meal delivery/i.test(r.category+' '+r.detail)))).forEach(r=>{const name=r.group==='Food'&&/eating out|restaurant|meal delivery/i.test(r.category+' '+r.detail)?'Eating out':r.category==='Groceries'?'Groceries':r.category==='Lawn services'?'Lawn services':billName(r);(bills[name]??=[]).push(r)});
 return Object.entries(bills).map(([name,rr])=>({name,rr,avg:months.length?sum(rr,'spend')/months.length:null,work:rr.some(r=>r.purpose==='Business'),group:rr[0].group,observedMonths:new Set(rr.map(r=>r.month)).size,latest:Math.abs([...rr].sort((a,b)=>b.date.localeCompare(a.date))[0].spend)}));
}
