const textSchema={type:'string'},countSchema={type:'integer',minimum:0};
export const recordSourceSchema={type:'object',additionalProperties:false,required:['canonical_record_id','reference_scope','references','reference_count','invalid_reference_count','declared_source_types','unknown_source_types','has_derivative_snapshot','custody_status','reported_origin','display_label','bank_match_verified','source_complete_verified','reconciliation_status'],properties:{
 canonical_record_id:textSchema,reference_scope:{type:'string',enum:['canonical_record','canonical_parent']},references:{type:'array',items:{type:'object',additionalProperties:false,required:['source_id','source_line','source_types','status'],properties:{source_id:textSchema,source_line:textSchema,source_types:{type:'array',items:textSchema},status:{type:'string',enum:['declared locator','conflicting declaration']}}}},reference_count:countSchema,invalid_reference_count:countSchema,declared_source_types:{type:'array',items:{type:'string',enum:['Era','Statement','Receipt','Snapshot']}},unknown_source_types:{type:'array',items:textSchema},has_derivative_snapshot:{type:'boolean'},custody_status:{type:'string',enum:['missing','derivative_only','declared_original_only','mixed','unresolved_declarations']},reported_origin:{type:['string','null']},display_label:textSchema,bank_match_verified:{type:'boolean',const:false},source_complete_verified:{type:'boolean',const:false},reconciliation_status:textSchema
},description:'record-source-evidence@1: locator counts are not corroboration; declared source types are not independent byte verification or accepted bank matches.'};
export function recordSourceEvidence(row){
 const known=new Set(['Era','Statement','Receipt','Snapshot']),byIdentity=new Map();let invalid=0;
 for(const ref of row.source_refs||[]){
  if(!ref||typeof ref.source_id!=='string'||!ref.source_id||typeof ref.source_line!=='string'||!ref.source_line){invalid++;continue;}
  const key=JSON.stringify([ref.source_id,ref.source_line]),entry=byIdentity.get(key)||{source_id:ref.source_id,source_line:ref.source_line,source_types:[]};
  const type=typeof ref.source_type==='string'&&ref.source_type?ref.source_type:'Unspecified';if(!entry.source_types.includes(type))entry.source_types.push(type);byIdentity.set(key,entry);
 }
 const references=[...byIdentity.values()].sort((a,b)=>{const left=JSON.stringify([a.source_id,a.source_line]),right=JSON.stringify([b.source_id,b.source_line]);return left<right?-1:left>right?1:0;}).map(ref=>({...ref,source_types:ref.source_types.sort(),status:ref.source_types.length>1?'conflicting declaration':'declared locator'}));
 const types=[...new Set(references.flatMap(ref=>ref.source_types))].sort(),unknown=types.filter(type=>!known.has(type)),snapshot=types.includes('Snapshot'),original=types.some(type=>known.has(type)&&type!=='Snapshot');
 const status=invalid||unknown.length||references.some(ref=>ref.source_types.length>1)?'unresolved_declarations':!references.length?'missing':snapshot&&original?'mixed':snapshot?'derivative_only':'declared_original_only';
 const labels={missing:'Source references unavailable',derivative_only:'Snapshot · derivative evidence',mixed:'Mixed declared sources · includes derivative evidence',declared_original_only:types.join(' + ')+' · declared evidence',unresolved_declarations:'Source declarations need review'};
 return {canonical_record_id:row.parent_transaction_id||row.id,reference_scope:row.parent_transaction_id&&row.parent_transaction_id!==row.id?'canonical_parent':'canonical_record',references,reference_count:references.length,invalid_reference_count:invalid,declared_source_types:types.filter(type=>known.has(type)),unknown_source_types:unknown,has_derivative_snapshot:snapshot,custody_status:status,reported_origin:typeof row.source==='string'?row.source:null,display_label:labels[status],bank_match_verified:false,source_complete_verified:false,reconciliation_status:'Bank matching and source completeness not certified'};
}
export function recordQuery(rows,months,options={}){
 if(options.record_ids!==undefined&&(!Array.isArray(options.record_ids)||options.record_ids.length>5000||options.record_ids.some(id=>typeof id!=='string')))throw Error('Invalid record selection');
 const search=(options.search||'').toLowerCase(),ids=options.record_ids?new Set(options.record_ids):null;
 if(search.length>300)throw Error('Search too long');
 const filtered=rows.filter(r=>(!ids||ids.has(r.id))&&(!search||String(r.merchant||'').concat(' ',r.description||'').toLowerCase().includes(search))&&(!options.account||r.account===options.account)&&(!options.purpose||r.purpose===options.purpose)&&(!options.month||r.month===options.month)).sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id));
 const offset=options.offset??0,limit=options.limit??100;
 if(!Number.isInteger(offset)||offset<0||!Number.isInteger(limit)||limit<1||limit>200)throw Error('Invalid record pagination');
 const spend=filtered.filter(r=>r.scope==='Household').reduce((n,r)=>n+Math.round((r.spend||0)*100),0);
 return {items:filtered.slice(offset,offset+limit).map(row=>({...structuredClone(row),source_evidence:recordSourceEvidence(row)})),total:filtered.length,offset,limit,next_offset:offset+limit<filtered.length?offset+limit:null,summary:{record_count:filtered.length,account_count:new Set(filtered.map(r=>r.account)).size,spending:{period_total:spend/100,recorded_average_per_selected_month:months.length?Math.round(spend/months.length)/100:null,status:'Recorded matching spending; source completeness unverified'}},complete:false};
}
