import {VERSION} from './core.mjs';
const string={type:'string'},integer={type:'integer'},classification={type:'object',properties:{group:string,category:string,purpose:{type:'string',enum:['Household','Personal','Business','Unresolved']}},required:['group','category','purpose'],additionalProperties:false};
export const toolDefinitions=[
 ['docs','Read capabilities, versions and limitations',{},[]],
 ['query','Read canonical transactions with bounded pagination',{month:string,account:string,purpose:string,offset:integer,limit:integer,collection:{type:'string',enum:['flows']},kind:string,view:{type:'string',enum:['dashboard']},scope:{type:'string',enum:['home','work','combined']},period:string,hide_reimbursed:{type:'boolean'},all:{type:'boolean'}},[]],
 ['summarize','Read recorded spending totals or shared monthly spending projection; no coverage claim',{month:string,account:string,purpose:string,view:{type:'string',enum:['spending']},months:{type:'array',items:string,minItems:1,maxItems:24},scope:{type:'string',enum:['home','work','combined']},collection:{type:'string',enum:['flows']},kind:string,period:string,hide_reimbursed:{type:'boolean'},group_by:{type:'array',items:{type:'string',enum:['month','kind','direction','family','purpose','group','category','account']}}},[]],
 ['coverage','Read source counts per account/month; counts are not completeness proof',{month:string,account:string,purpose:string},[]],
 ['export','Export the ledger and evidence; may contain private financial data',{},[]],
 ['import_preview','Validate a normalized import without changing data',{rows:{type:'array',items:{type:'object'}},format:{type:'string',enum:['dashboard_snapshot']},snapshot:{type:'object'}},[]],
 ['import_commit','Commit normalized source records without duplicate spending',{revision:integer,idempotency_key:string,rows:{type:'array',items:{type:'object'}},format:{type:'string',enum:['dashboard_snapshot']},snapshot:{type:'object'}},['revision','idempotency_key']],
 ['classification_propose','Store a review-only classification proposal',{revision:integer,transaction_id:string},['revision','transaction_id']],
 ['classification_review','Accept or reject a proposal with evidence and a revision check',{revision:integer,proposal_id:string,decision:{type:'string',enum:['accept','reject']},classification,evidence:string},['revision','proposal_id','decision','evidence']]
].map(([name,description,properties,required])=>({name,description,inputSchema:{type:'object',properties,required,additionalProperties:false},annotations:{readOnlyHint:!['import_commit','classification_propose','classification_review'].includes(name),destructiveHint:name==='classification_review',idempotentHint:['docs','query','summarize','coverage','export','import_preview','import_commit'].includes(name),openWorldHint:false}}));
export async function rpc(message,call){const {id,method,params={}}=message;if(id===undefined)return null;try{let result;if(method==='initialize')result={protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'finance-core-prototype',version:VERSION}};else if(method==='ping')result={};else if(method==='tools/list')result={tools:toolDefinitions};else if(method==='tools/call'){if(!toolDefinitions.some(t=>t.name===params.name))throw Error('Unknown tool');const data=await call(params.name,params.arguments||{});result={content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data};}else return{jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}};return{jsonrpc:'2.0',id,result};}catch(e){return{jsonrpc:'2.0',id,result:{isError:true,content:[{type:'text',text:e.message}]}};}}
