import {classificationSchema} from './classification-contract.mjs';
import {VERSION} from './core.mjs';
const string={type:'string'},integer={type:'integer'},classification=classificationSchema;
export const operationDefinitions=[
 ['docs','Read capabilities, versions and limitations',{},[]],
 ['query','Read canonical transactions with bounded pagination',{record_ids:{type:'array',items:string,maxItems:5000},search:string,month:string,account:string,purpose:string,offset:integer,limit:integer,collection:{type:'string',enum:['flows','ledger','snapshot','records']},kind:string,view:{type:'string',enum:['dashboard']},scope:{type:'string',enum:['home','work','combined']},period:string,hide_reimbursed:{type:'boolean'},all:{type:'boolean'}},[]],
 ['summarize','Read recorded spending totals or shared monthly spending projection; no coverage claim',{account_type:{type:'string',enum:['credit_card','loan','bank']},month:string,account:string,purpose:string,view:{type:'string',enum:['spending']},months:{type:'array',items:string,minItems:1,maxItems:24},scope:{type:'string',enum:['home','work','combined']},collection:{type:'string',enum:['flows','commitments','evidence','accounts']},kind:string,period:string,hide_reimbursed:{type:'boolean'},groups:{type:'array',items:string,maxItems:100},series:{type:'boolean'},rollups:{type:'array',maxItems:8,items:{type:'array',minItems:1,maxItems:12,items:{type:'string',enum:['kind','direction','family','purpose','group','category','account','merchant','detail','travel_purpose','payment_channel']}}},series_by:{type:'array',items:{type:'string',enum:['kind','direction','family','purpose','group','category','account','merchant','detail','travel_purpose','payment_channel']}},group_by:{type:'array',items:{type:'string',enum:['month','kind','direction','family','purpose','group','category','account','merchant','detail','travel_purpose','payment_channel']}}},[]],
 ['coverage','Read source counts per account/month; counts are not completeness proof',{month:string,account:string,purpose:string},[]],
 ['export','Export the ledger and evidence; may contain private financial data',{},[]],
 ['import_preview','Validate a normalized import without changing data',{rows:{type:'array',items:{type:'object'}},format:{type:'string',enum:['dashboard_snapshot','runtime_evidence']},snapshot:{type:'object'},evidence:{type:'object'}},[]],
 ['import_commit','Commit normalized source records without duplicate spending',{revision:integer,idempotency_key:string,rows:{type:'array',items:{type:'object'}},format:{type:'string',enum:['dashboard_snapshot','runtime_evidence']},snapshot:{type:'object'},evidence:{type:'object'}},['revision','idempotency_key']],
 ['classification_propose','Store a review-only classification proposal',{revision:integer,transaction_id:string},['revision','transaction_id']],
 ['decision_update','Save dashboard curation and budget decisions with evidence history',{revision:integer,decisions:{type:'object',properties:{transactions:{type:'object'},budgets:{type:'object'},commitments:{type:'object'},notes:string},required:['transactions','budgets','commitments','notes'],additionalProperties:false}},['revision','decisions']],
 ['classification_review','Accept or reject a proposal with evidence and a revision check',{revision:integer,proposal_id:string,decision:{type:'string',enum:['accept','reject']},classification,evidence:string},['revision','proposal_id','decision','evidence']]
].map(([name,description,properties,required])=>({name,description,inputSchema:{type:'object',properties,required,additionalProperties:false},annotations:{readOnlyHint:!['import_commit','classification_propose','classification_review','decision_update'].includes(name),destructiveHint:name==='classification_review',idempotentHint:['docs','query','summarize','coverage','export','import_preview','import_commit'].includes(name),openWorldHint:false}}));
export const toolDefinitions=[
 {name:'docs',description:'Discover all operation schemas, effects, versions and limits',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
 {name:'query',description:'Read canonical facts or composed flow collections with bounded filters',inputSchema:operationDefinitions.find(x=>x.name==='query').inputSchema,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
 {name:'project',description:'Produce pure summaries, source coverage or import previews; never writes',inputSchema:{type:'object',properties:{operation:{type:'string',enum:['summarize','coverage','import_preview']},args:{type:'object'}},required:['operation','args'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
 {name:'execute',description:'Run an explicit authenticated, revisioned import or curation command; no financial transactions',inputSchema:{type:'object',properties:{operation:{type:'string',enum:['import_commit','classification_propose','classification_review','decision_update']},args:{type:'object'}},required:['operation','args'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:false,openWorldHint:true}}
];
function validateSchema(value,schema,path='args',depth=0){
 if(depth>30)throw Error('Input nesting limit');
 if(schema.type==='object'){if(!value||typeof value!=='object'||Array.isArray(value))throw Error(path+' must be an object');for(const key of schema.required||[])if(!Object.hasOwn(value,key))throw Error(path+'.'+key+' is required');for(const [key,child] of Object.entries(value)){if(['__proto__','constructor','prototype'].includes(key))throw Error('Reserved input key');const next=schema.properties?.[key];if(!next&&schema.additionalProperties===false)throw Error('Unknown argument: '+path+'.'+key);if(next)validateSchema(child,next,path+'.'+key,depth+1);}}
 else if(schema.type==='array'){if(!Array.isArray(value)||schema.minItems&&value.length<schema.minItems||schema.maxItems&&value.length>schema.maxItems)throw Error(path+' must be a bounded array');if(schema.items)value.forEach((v,i)=>validateSchema(v,schema.items,path+'['+i+']',depth+1));}
 else if(schema.type==='integer'){if(!Number.isInteger(value))throw Error(path+' must be an integer');}
 else if(schema.type&&typeof value!==schema.type)throw Error(path+' must be '+schema.type);
 if(schema.enum&&!schema.enum.includes(value))throw Error('Invalid option: '+path);
}
export async function dispatch(name,args,call){
 const method=toolDefinitions.find(x=>x.name===name);if(!method)throw Error('Unknown capability');validateSchema(args||{},method.inputSchema);
 if(name==='docs')return {...await call('docs',{}),surface:toolDefinitions,operations:operationDefinitions};
 const operation=name==='query'?'query':args.operation,parameters=name==='query'?args:args.args;
 const definition=operationDefinitions.find(x=>x.name===operation);if(!definition)throw Error('Unknown operation');validateSchema(parameters,definition.inputSchema);return call(operation,parameters);
}
export async function rpc(message,call){const {id,method,params={}}=message;if(id===undefined)return null;try{let result;if(method==='initialize')result={protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'finance-core-prototype',version:VERSION}};else if(method==='ping')result={};else if(method==='tools/list')result={tools:toolDefinitions};else if(method==='tools/call'){if(!toolDefinitions.some(t=>t.name===params.name))throw Error('Unknown tool');const data=await dispatch(params.name,params.arguments||{},call);result={content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data};}else return{jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}};return{jsonrpc:'2.0',id,result};}catch(e){return{jsonrpc:'2.0',id,result:{isError:true,content:[{type:'text',text:e.message}]}};}}
